// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QcEntity = global::QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionModel;
using QuickCode.Demo.PricingEngineModule.Application.Mappings;
using QuickCode.Demo.PricingEngineModule.Persistence.Sql;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Persistence.Repositories
{
    public partial class CommissionModelRepository : BaseRepository, ICommissionModelRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CommissionModelRepository(ILogger<CommissionModelRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CommissionModel")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CommissionModelDto>> InsertAsync(CommissionModelDto value)
        {
            return await ExecuteWithExceptionHandling(CommissionModelCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionModel.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CommissionModelCrudSqlBindings.ParameterNamePrefix, value, CommissionModelCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CommissionModel>(sql, p);
                return new RepoResponse<CommissionModelDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CommissionModelDto value)
        {
            return await ExecuteWithExceptionHandling(CommissionModelCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionModel.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CommissionModelCrudSqlBindings.ParameterNamePrefix, value, CommissionModelCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CommissionModelDto value)
        {
            return await ExecuteWithExceptionHandling(CommissionModelCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionModel.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CommissionModelCrudSqlBindings.ParameterNamePrefix, value, CommissionModelCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CommissionModelDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CommissionModelCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionModel.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CommissionModelCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CommissionModel>(sql, p);
                return row == null ? CreateNotFoundResponse<CommissionModelDto>("Not found in CommissionModel") : new RepoResponse<CommissionModelDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CommissionModelDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CommissionModelCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CommissionModelDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CommissionModel.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CommissionModel>(sql, p);
                return new RepoResponse<List<CommissionModelDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CommissionModelCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionModel.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}