// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.IdentityModule.Application.Dtos.AspNetUserRole;
using AspNetUserRoleEntity = QuickCode.Demo.IdentityModule.Domain.Entities.AspNetUserRole;
using QuickCode.Demo.IdentityModule.Domain.Enums;

namespace QuickCode.Demo.IdentityModule.Application.Mappings
{
    public static class AspNetUserRoleMappings
    {
        public static List<AspNetUserRoleDto> ToDto(this IEnumerable<AspNetUserRoleEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AspNetUserRoleDto ToDto(this AspNetUserRoleEntity model)
        {
            return new AspNetUserRoleDto
            {
                UserId = model.UserId,
                RoleId = model.RoleId
            };
        }

        public static AspNetUserRoleEntity ToEntity(this AspNetUserRoleDto model)
        {
            return new AspNetUserRoleEntity
            {
                UserId = model.UserId,
                RoleId = model.RoleId
            };
        }
    }
}