// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.IdentityModule.Application.Dtos.TableComboboxSetting;
using TableComboboxSettingEntity = QuickCode.Demo.IdentityModule.Domain.Entities.TableComboboxSetting;
using QuickCode.Demo.IdentityModule.Domain.Enums;

namespace QuickCode.Demo.IdentityModule.Application.Mappings
{
    public static class TableComboboxSettingMappings
    {
        public static List<TableComboboxSettingDto> ToDto(this IEnumerable<TableComboboxSettingEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TableComboboxSettingDto ToDto(this TableComboboxSettingEntity model)
        {
            return new TableComboboxSettingDto
            {
                TableName = model.TableName,
                IdColumn = model.IdColumn,
                TextColumns = model.TextColumns,
                StringFormat = model.StringFormat
            };
        }

        public static TableComboboxSettingEntity ToEntity(this TableComboboxSettingDto model)
        {
            return new TableComboboxSettingEntity
            {
                TableName = model.TableName,
                IdColumn = model.IdColumn,
                TextColumns = model.TextColumns,
                StringFormat = model.StringFormat
            };
        }
    }
}