-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [PRODUCT_CATEGORIES] 
WHERE [PRODUCT_ID] = @PRM_PRODUCT_CATEGORY_PRODUCT_ID 
	AND [CATEGORY_ID] = @PRM_PRODUCT_CATEGORY_CATEGORY_ID