// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CategoryCommissionOverride;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CategoryCommissionOverride
{
    public class GetByCategoryIdQuery : IRequest<Response<GetByCategoryIdResponseDto>>
    {
        public int CategoryCommissionOverrideCategoryId { get; set; }

        public GetByCategoryIdQuery(int categoryCommissionOverrideCategoryId)
        {
            this.CategoryCommissionOverrideCategoryId = categoryCommissionOverrideCategoryId;
        }

        public class GetByCategoryIdHandler : IRequestHandler<GetByCategoryIdQuery, Response<GetByCategoryIdResponseDto>>
        {
            private readonly ILogger<GetByCategoryIdHandler> _logger;
            private readonly ICategoryCommissionOverrideRepository _repository;
            public GetByCategoryIdHandler(ILogger<GetByCategoryIdHandler> logger, ICategoryCommissionOverrideRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<GetByCategoryIdResponseDto>> Handle(GetByCategoryIdQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByCategoryIdAsync(request.CategoryCommissionOverrideCategoryId);
                return returnValue.ToResponse();
            }
        }
    }
}