IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PROMOTIONAL_CAMPAIGNS', N'U') AND name = N'IX_PROMOTIONAL_CAMPAIGNS_IsDeleted')
BEGIN
    CREATE INDEX [IX_PROMOTIONAL_CAMPAIGNS_IsDeleted] ON [dbo].[PROMOTIONAL_CAMPAIGNS] ([IsDeleted]);
END