IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_COMMISSION_OVERRIDES', N'U') AND name = N'IX_CATEGORY_COMMISSION_OVERRIDES_CATEGORY_ID')
BEGIN
    CREATE INDEX [IX_CATEGORY_COMMISSION_OVERRIDES_CATEGORY_ID] ON [dbo].[CATEGORY_COMMISSION_OVERRIDES] ([CATEGORY_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_COMMISSION_OVERRIDES', N'U') AND name = N'IX_CATEGORY_COMMISSION_OVERRIDES_COMMISSION_MODEL_ID')
BEGIN
    CREATE INDEX [IX_CATEGORY_COMMISSION_OVERRIDES_COMMISSION_MODEL_ID] ON [dbo].[CATEGORY_COMMISSION_OVERRIDES] ([COMMISSION_MODEL_ID]);
END