IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORY_COMMISSION_OVERRIDES', N'U') AND name = N'IX_CATEGORY_COMMISSION_OVERRIDES_IsDeleted')
BEGIN
    CREATE INDEX [IX_CATEGORY_COMMISSION_OVERRIDES_IsDeleted] ON [dbo].[CATEGORY_COMMISSION_OVERRIDES] ([IsDeleted]);
END