IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_COMMISSION_OVERRIDES_COMMISSION_MODELS_COMMISSION_MODEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_COMMISSION_OVERRIDES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_COMMISSION_OVERRIDES] ADD CONSTRAINT [FK_CATEGORY_COMMISSION_OVERRIDES_COMMISSION_MODELS_COMMISSION_MODEL_ID] FOREIGN KEY ([COMMISSION_MODEL_ID]) REFERENCES [dbo].[COMMISSION_MODELS] ([ID]);
END