IF OBJECT_ID(N'dbo.SELLER_COMMISSION_ASSIGNMENTS', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[SELLER_COMMISSION_ASSIGNMENTS] (
        [SELLER_ID] int NOT NULL,
        [COMMISSION_MODEL_ID] int NOT NULL,
        [EFFECTIVE_DATE] datetime2(7) NOT NULL,
        CONSTRAINT [PK_SELLER_COMMISSION_ASSIGNMENTS] PRIMARY KEY ([SELLER_ID])
    );
END;