IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_RULES', N'U') AND name = N'IX_COMMISSION_RULES_IsDeleted')
BEGIN
    CREATE INDEX [IX_COMMISSION_RULES_IsDeleted] ON [dbo].[COMMISSION_RULES] ([IsDeleted]);
END