IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CAMPAIGN_APPLICABILITIES_PROMOTIONAL_CAMPAIGNS_CAMPAIGN_ID' AND parent_object_id = OBJECT_ID(N'dbo.CAMPAIGN_APPLICABILITIES'))
BEGIN
    ALTER TABLE [dbo].[CAMPAIGN_APPLICABILITIES] ADD CONSTRAINT [FK_CAMPAIGN_APPLICABILITIES_PROMOTIONAL_CAMPAIGNS_CAMPAIGN_ID] FOREIGN KEY ([CAMPAIGN_ID]) REFERENCES [dbo].[PROMOTIONAL_CAMPAIGNS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORY_COMMISSION_OVERRIDES_COMMISSION_MODELS_COMMISSION_MODEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORY_COMMISSION_OVERRIDES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORY_COMMISSION_OVERRIDES] ADD CONSTRAINT [FK_CATEGORY_COMMISSION_OVERRIDES_COMMISSION_MODELS_COMMISSION_MODEL_ID] FOREIGN KEY ([COMMISSION_MODEL_ID]) REFERENCES [dbo].[COMMISSION_MODELS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMISSION_RULES_COMMISSION_MODELS_COMMISSION_MODEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMISSION_RULES'))
BEGIN
    ALTER TABLE [dbo].[COMMISSION_RULES] ADD CONSTRAINT [FK_COMMISSION_RULES_COMMISSION_MODELS_COMMISSION_MODEL_ID] FOREIGN KEY ([COMMISSION_MODEL_ID]) REFERENCES [dbo].[COMMISSION_MODELS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_COMMISSION_ASSIGNMENTS_COMMISSION_MODELS_COMMISSION_MODEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_COMMISSION_ASSIGNMENTS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_COMMISSION_ASSIGNMENTS] ADD CONSTRAINT [FK_SELLER_COMMISSION_ASSIGNMENTS_COMMISSION_MODELS_COMMISSION_MODEL_ID] FOREIGN KEY ([COMMISSION_MODEL_ID]) REFERENCES [dbo].[COMMISSION_MODELS] ([ID]);
END