IF OBJECT_ID(N'dbo.CAMPAIGN_APPLICABILITIES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[CAMPAIGN_APPLICABILITIES] (
        [CAMPAIGN_ID] int NOT NULL,
        [SCOPE] nvarchar(50) NOT NULL,
        [SCOPE_ID] int NOT NULL,
        CONSTRAINT [PK_CAMPAIGN_APPLICABILITIES] PRIMARY KEY ([CAMPAIGN_ID], [SCOPE], [SCOPE_ID])
    );
END;