IF OBJECT_ID(N'dbo.CATEGORY_COMMISSION_OVERRIDES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[CATEGORY_COMMISSION_OVERRIDES] (
        [ID] int IDENTITY(1,1) NOT NULL,
        [CATEGORY_ID] int NOT NULL,
        [COMMISSION_MODEL_ID] int NOT NULL,
        [EFFECTIVE_DATE] datetime2(7) NOT NULL,
        [IsDeleted] bit NOT NULL DEFAULT 0,
        [DeletedOnUtc] datetime2(7) NULL,
        CONSTRAINT [PK_CATEGORY_COMMISSION_OVERRIDES] PRIMARY KEY ([ID])
    );
END;