IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_MODELS', N'U') AND name = N'IX_COMMISSION_MODELS_IsDeleted')
BEGIN
    CREATE INDEX [IX_COMMISSION_MODELS_IsDeleted] ON [dbo].[COMMISSION_MODELS] ([IsDeleted]);
END