IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_COMMISSION_RULES_COMMISSION_MODELS_COMMISSION_MODEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.COMMISSION_RULES'))
BEGIN
    ALTER TABLE [dbo].[COMMISSION_RULES] ADD CONSTRAINT [FK_COMMISSION_RULES_COMMISSION_MODELS_COMMISSION_MODEL_ID] FOREIGN KEY ([COMMISSION_MODEL_ID]) REFERENCES [dbo].[COMMISSION_MODELS] ([ID]);
END