IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_RULES', N'U') AND name = N'IX_COMMISSION_RULES_COMMISSION_MODEL_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_COMMISSION_RULES_COMMISSION_MODEL_ID_IS_ACTIVE] ON [dbo].[COMMISSION_RULES] ([COMMISSION_MODEL_ID], [IS_ACTIVE]);
END