IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CAMPAIGN_APPLICABILITIES_PROMOTIONAL_CAMPAIGNS_CAMPAIGN_ID' AND parent_object_id = OBJECT_ID(N'dbo.CAMPAIGN_APPLICABILITIES'))
BEGIN
    ALTER TABLE [dbo].[CAMPAIGN_APPLICABILITIES] ADD CONSTRAINT [FK_CAMPAIGN_APPLICABILITIES_PROMOTIONAL_CAMPAIGNS_CAMPAIGN_ID] FOREIGN KEY ([CAMPAIGN_ID]) REFERENCES [dbo].[PROMOTIONAL_CAMPAIGNS] ([ID]);
END