IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_COMMISSION_ASSIGNMENTS', N'U') AND name = N'IX_SELLER_COMMISSION_ASSIGNMENTS_COMMISSION_MODEL_ID')
BEGIN
    CREATE INDEX [IX_SELLER_COMMISSION_ASSIGNMENTS_COMMISSION_MODEL_ID] ON [dbo].[SELLER_COMMISSION_ASSIGNMENTS] ([COMMISSION_MODEL_ID]);
END