IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_COMMISSION_ASSIGNMENTS_COMMISSION_MODELS_COMMISSION_MODEL_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_COMMISSION_ASSIGNMENTS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_COMMISSION_ASSIGNMENTS] ADD CONSTRAINT [FK_SELLER_COMMISSION_ASSIGNMENTS_COMMISSION_MODELS_COMMISSION_MODEL_ID] FOREIGN KEY ([COMMISSION_MODEL_ID]) REFERENCES [dbo].[COMMISSION_MODELS] ([ID]);
END