// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.PricingEngineModule.Application.Features.SellerCommissionAssignment;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.SellerCommissionAssignment;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.Infrastructure.Web.Helpers;
using QuickCode.Demo.Application.Contracts;

namespace QuickCode.Demo.PricingEngineModule.Application.Tests.Features.SellerCommissionAssignment
{
    public class UpdateSellerCommissionAssignmentCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<ISellerCommissionAssignmentRepository> _repositoryMock;
        private readonly Mock<ILogger<UpdateSellerCommissionAssignmentCommand.UpdateSellerCommissionAssignmentHandler>> _loggerMock;
        public UpdateSellerCommissionAssignmentCommandTests()
        {
            _repositoryMock = new Mock<ISellerCommissionAssignmentRepository>();
            _loggerMock = new Mock<ILogger<UpdateSellerCommissionAssignmentCommand.UpdateSellerCommissionAssignmentHandler>>();
        }

        [Fact]
        public async Task Handle_Should_Return_Success_When_Valid_Command()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<SellerCommissionAssignmentDto>("tr");
            var fakeResponse = new RepoResponse<bool>(true, "Success");
            _repositoryMock.Setup(r => r.UpdateAsync(It.IsAny<SellerCommissionAssignmentDto>())).ReturnsAsync(fakeResponse);
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.SellerId)).ReturnsAsync(new RepoResponse<SellerCommissionAssignmentDto>());
            var handler = new UpdateSellerCommissionAssignmentCommand.UpdateSellerCommissionAssignmentHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new UpdateSellerCommissionAssignmentCommand(fakeDto.SellerId, fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.True(result.Value);
            _repositoryMock.Verify(r => r.UpdateAsync(It.IsAny<SellerCommissionAssignmentDto>()), Times.Once);
        }

        [Fact]
        public async Task Handle_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<SellerCommissionAssignmentDto>("tr");
            var fakeResponse = new RepoResponse<bool>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.UpdateAsync(It.IsAny<SellerCommissionAssignmentDto>())).ReturnsAsync(fakeResponse);
            _repositoryMock.Setup(r => r.GetByPkAsync(fakeDto.SellerId)).ReturnsAsync(new RepoResponse<SellerCommissionAssignmentDto>());
            var handler = new UpdateSellerCommissionAssignmentCommand.UpdateSellerCommissionAssignmentHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new UpdateSellerCommissionAssignmentCommand(fakeDto.SellerId, fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.False(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}