-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [TRANSACTION_LEDGERS] 
	SET [DESCRIPTION] = @TRANSACTION_LEDGER_DESCRIPTION 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_TRANSACTION_LEDGER_ID