// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.SellerPayout
{
    public class CancelCommand : IRequest<Response<int>>
    {
        public int SellerPayoutId { get; set; }
        public CancelRequestDto UpdateRequest { get; set; }

        public CancelCommand(int sellerPayoutId, CancelRequestDto updateRequest)
        {
            this.SellerPayoutId = sellerPayoutId;
            this.UpdateRequest = updateRequest;
        }

        public class CancelHandler : IRequestHandler<CancelCommand, Response<int>>
        {
            private readonly ILogger<CancelHandler> _logger;
            private readonly ISellerPayoutRepository _repository;
            public CancelHandler(ILogger<CancelHandler> logger, ISellerPayoutRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(CancelCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.CancelAsync(request.SellerPayoutId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}