// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.SellerPayout
{
    public class UpdateSellerPayoutCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }
        public SellerPayoutDto request { get; set; }

        public UpdateSellerPayoutCommand(int id, SellerPayoutDto request)
        {
            this.request = request;
            this.Id = id;
        }

        public class UpdateSellerPayoutHandler : IRequestHandler<UpdateSellerPayoutCommand, Response<bool>>
        {
            private readonly ILogger<UpdateSellerPayoutHandler> _logger;
            private readonly ISellerPayoutRepository _repository;
            public UpdateSellerPayoutHandler(ILogger<UpdateSellerPayoutHandler> logger, ISellerPayoutRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdateSellerPayoutCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.Id);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}