// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;
using Moq;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.FinanceSettlementModule.Application.Features.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.Infrastructure.Web.Helpers;
using QuickCode.Demo.Application.Contracts;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Tests.Features.SellerPayout
{
    public class InsertSellerPayoutCommandTests : IDisposable
    {
        private const int ResultCodeSuccess = 0;
        private const int ResultCodeNotFound = 404;
        private readonly Mock<ISellerPayoutRepository> _repositoryMock;
        private readonly Mock<ILogger<InsertSellerPayoutCommand.InsertSellerPayoutHandler>> _loggerMock;
        public InsertSellerPayoutCommandTests()
        {
            _repositoryMock = new Mock<ISellerPayoutRepository>();
            _loggerMock = new Mock<ILogger<InsertSellerPayoutCommand.InsertSellerPayoutHandler>>();
        }

        [Fact]
        public async Task Handle_Should_Return_Success_When_Valid_Command()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<SellerPayoutDto>("tr");
            var fakeResponse = new RepoResponse<SellerPayoutDto>(fakeDto, "Success");
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<SellerPayoutDto>())).ReturnsAsync(fakeResponse);
            var handler = new InsertSellerPayoutCommand.InsertSellerPayoutHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new InsertSellerPayoutCommand(fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeSuccess, result.Code);
            Assert.Equal(fakeDto, result.Value);
            _repositoryMock.Verify(r => r.InsertAsync(It.IsAny<SellerPayoutDto>()), Times.Once);
        }

        [Fact]
        public async Task Handle_Should_Return_NotFound_When_Repository_Returns_404()
        {
            // Arrange
            var fakeDto = TestDataGenerator.CreateFake<SellerPayoutDto>("tr");
            var fakeResponse = new RepoResponse<SellerPayoutDto>
            {
                Code = ResultCodeNotFound,
                Message = "Not found"
            };
            _repositoryMock.Setup(r => r.InsertAsync(It.IsAny<SellerPayoutDto>())).ReturnsAsync(fakeResponse);
            var handler = new InsertSellerPayoutCommand.InsertSellerPayoutHandler(_loggerMock.Object, _repositoryMock.Object);
            var command = new InsertSellerPayoutCommand(fakeDto);
            // Act
            var result = await handler.Handle(command, CancellationToken.None);
            // Assert
            Assert.Equal(ResultCodeNotFound, result.Code);
            Assert.Null(result.Value);
        }

        public void Dispose()
        {
        // Cleanup handled by xUnit
        }
    }
}