// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.AttributeValue;
using System.Threading.Tasks;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface IAttributeValueRepository : IBaseRepository<AttributeValueDto>
    {
        Task<RepoResponse<AttributeValueDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByAttributeIdResponseDto>>> GetByAttributeIdAsync(int attributeValueAttributeId, int? pageNumber = null, int? pageSize = null);
    }
}