// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Category;
using System.Threading.Tasks;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface ICategoryRepository : IBaseRepository<CategoryDto>
    {
        Task<RepoResponse<CategoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetSubCategoriesResponseDto>>> GetSubCategoriesAsync(int categoryParentCategoryId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetBySlugResponseDto>> GetBySlugAsync(string categorySlug);
        Task<RepoResponse<int>> DeactivateAsync(int categoryId, DeactivateRequestDto updateRequest);
    }
}