// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Product;
using System.Threading.Tasks;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories
{
    public partial interface IProductRepository : IBaseRepository<ProductDto>
    {
        Task<RepoResponse<ProductDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetBySkuResponseDto>> GetBySkuAsync(string productSku);
        Task<RepoResponse<List<GetActiveBySellerResponseDto>>> GetActiveBySellerAsync(int productSellerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchProductsResponseDto>>> SearchProductsAsync(string productName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetFeaturedResponseDto>>> GetFeaturedAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetProductsWithDetailsResponseDto>>> GetProductsWithDetailsAsync(int productsBrandId, int productPrimaryCategoryId, int categoryId, int brandId, int productsPrimaryCategoryId, int productBrandId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetCountByStatusResponseDto>> GetCountByStatusAsync(ProductStatus productStatus);
        Task<RepoResponse<int>> ApproveAsync(int productId, ApproveRequestDto updateRequest);
        Task<RepoResponse<int>> RejectAsync(int productId, RejectRequestDto updateRequest);
        Task<RepoResponse<int>> SetFeaturedAsync(int productId, SetFeaturedRequestDto updateRequest);
    }
}