-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 [STATUS], COUNT(*) AS COUNT 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STATUS] = @PRM_PRODUCT_STATUS 
GROUP BY P.[STATUS] 
ORDER BY P.[STATUS] 