-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT P.[ID], P.[SKU], P.[NAME], P.[SELLER_ID], P.[PHOTO], P.[VIDEO], P.[DATASHEET] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STATUS] = 'PendingApproval' 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 