// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Web.Controllers;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.PayoutReport;
using QuickCode.Demo.FinanceSettlementModule.Application.Features.PayoutReport;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Api.Controllers
{
    public partial class PayoutReportsController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<PayoutReportsController> logger;
        private readonly IServiceProvider serviceProvider;
        public PayoutReportsController(IMediator mediator, IServiceProvider serviceProvider, ILogger<PayoutReportsController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListResult<PayoutReportDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size, [FromQuery] bool includeCount = false)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListPayoutReportQuery(page, size, includeCount));
            if (HandleResponseError(response, logger, "PayoutReport", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountPayoutReportQuery());
            if (HandleResponseError(response, logger, "PayoutReport") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(PayoutReportDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemPayoutReportQuery(id));
            if (HandleResponseError(response, logger, "PayoutReport", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(PayoutReportDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(PayoutReportDto model)
        {
            var response = await mediator.Send(new InsertPayoutReportCommand(model));
            if (HandleResponseError(response, logger, "PayoutReport") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, PayoutReportDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdatePayoutReportCommand(id, model));
            if (HandleResponseError(response, logger, "PayoutReport", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemPayoutReportCommand(id));
            if (HandleResponseError(response, logger, "PayoutReport", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-period/{payoutReportPayoutPeriodId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByPeriodResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByPeriodAsync(int payoutReportPayoutPeriodId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByPeriodQuery(payoutReportPayoutPeriodId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PayoutReport", $"PayoutReportPayoutPeriodId: '{payoutReportPayoutPeriodId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-recent-reports")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetRecentReportsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetRecentReportsAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetRecentReportsQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PayoutReport", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-latest-report")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetLatestReportResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetLatestReportAsync()
        {
            var response = await mediator.Send(new GetLatestReportQuery());
            if (HandleResponseError(response, logger, "PayoutReport", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}