// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Web.Controllers;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Application.Features.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Api.Controllers
{
    public partial class SellerPayoutsController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<SellerPayoutsController> logger;
        private readonly IServiceProvider serviceProvider;
        public SellerPayoutsController(IMediator mediator, IServiceProvider serviceProvider, ILogger<SellerPayoutsController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListResult<SellerPayoutDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size, [FromQuery] bool includeCount = false)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListSellerPayoutQuery(page, size, includeCount));
            if (HandleResponseError(response, logger, "SellerPayout", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountSellerPayoutQuery());
            if (HandleResponseError(response, logger, "SellerPayout") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(SellerPayoutDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemSellerPayoutQuery(id));
            if (HandleResponseError(response, logger, "SellerPayout", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(SellerPayoutDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(SellerPayoutDto model)
        {
            var response = await mediator.Send(new InsertSellerPayoutCommand(model));
            if (HandleResponseError(response, logger, "SellerPayout") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, SellerPayoutDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdateSellerPayoutCommand(id, model));
            if (HandleResponseError(response, logger, "SellerPayout", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemSellerPayoutCommand(id));
            if (HandleResponseError(response, logger, "SellerPayout", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-seller-id/{sellerPayoutSellerId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetBySellerIdResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetBySellerIdAsync(int sellerPayoutSellerId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetBySellerIdQuery(sellerPayoutSellerId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutSellerId: '{sellerPayoutSellerId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-status/{sellerPayoutStatus}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByStatusResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByStatusAsync(PayoutStatus sellerPayoutStatus, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByStatusQuery(sellerPayoutStatus, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutStatus: '{sellerPayoutStatus}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-with-period/{sellerPayoutsPayoutPeriodId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetWithPeriodResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetWithPeriodAsync(int sellerPayoutsPayoutPeriodId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetWithPeriodQuery(sellerPayoutsPayoutPeriodId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutsPayoutPeriodId: '{sellerPayoutsPayoutPeriodId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-pending-payouts")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetPendingPayoutsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPendingPayoutsAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetPendingPayoutsQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-pending-payouts-summary")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetPendingPayoutsSummaryResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPendingPayoutsSummaryAsync()
        {
            var response = await mediator.Send(new GetPendingPayoutsSummaryQuery());
            if (HandleResponseError(response, logger, "SellerPayout", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-approved-payouts")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetApprovedPayoutsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetApprovedPayoutsAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetApprovedPayoutsQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-paid-summary")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetPaidSummaryResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetPaidSummaryAsync()
        {
            var response = await mediator.Send(new GetPaidSummaryQuery());
            if (HandleResponseError(response, logger, "SellerPayout", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-failed-payouts")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetFailedPayoutsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetFailedPayoutsAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetFailedPayoutsQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-period/{sellerPayoutPayoutPeriodId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetByPeriodResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByPeriodAsync(int sellerPayoutPayoutPeriodId, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetByPeriodQuery(sellerPayoutPayoutPeriodId, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutPayoutPeriodId: '{sellerPayoutPayoutPeriodId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("approve/{sellerPayoutId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ApproveAsync(int sellerPayoutId, [FromBody] ApproveRequestDto updateRequest)
        {
            var response = await mediator.Send(new ApproveCommand(sellerPayoutId, updateRequest));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutId: '{sellerPayoutId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-as-processing/{sellerPayoutId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkAsProcessingAsync(int sellerPayoutId, [FromBody] MarkAsProcessingRequestDto updateRequest)
        {
            var response = await mediator.Send(new MarkAsProcessingCommand(sellerPayoutId, updateRequest));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutId: '{sellerPayoutId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-as-paid/{sellerPayoutId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkAsPaidAsync(int sellerPayoutId, [FromBody] MarkAsPaidRequestDto updateRequest)
        {
            var response = await mediator.Send(new MarkAsPaidCommand(sellerPayoutId, updateRequest));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutId: '{sellerPayoutId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("mark-as-failed/{sellerPayoutId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> MarkAsFailedAsync(int sellerPayoutId, [FromBody] MarkAsFailedRequestDto updateRequest)
        {
            var response = await mediator.Send(new MarkAsFailedCommand(sellerPayoutId, updateRequest));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutId: '{sellerPayoutId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("cancel/{sellerPayoutId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CancelAsync(int sellerPayoutId, [FromBody] CancelRequestDto updateRequest)
        {
            var response = await mediator.Send(new CancelCommand(sellerPayoutId, updateRequest));
            if (HandleResponseError(response, logger, "SellerPayout", $"SellerPayoutId: '{sellerPayoutId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}