-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[PROMOTIONAL_CAMPAIGNS] (
    [NAME],
    [START_DATE],
    [END_DATE],
    [DISCOUNT_PERCENTAGE],
    [IS_ACTIVE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_PROMOTIONAL_CAMPAIGN_NAME,
    @PRM_PROMOTIONAL_CAMPAIGN_START_DATE,
    @PRM_PROMOTIONAL_CAMPAIGN_END_DATE,
    @PRM_PROMOTIONAL_CAMPAIGN_DISCOUNT_PERCENTAGE,
    @PRM_PROMOTIONAL_CAMPAIGN_IS_ACTIVE
    );