-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
-- PK-only: relink = DELETE existing row, INSERT new row (same pattern as EF many-to-many).
DELETE FROM [dbo].[CAMPAIGN_APPLICABILITIES]
WHERE
    [CAMPAIGN_ID] = @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID_REMOVE AND
    [SCOPE] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE_REMOVE AND
    [SCOPE_ID] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ID_REMOVE
    AND EXISTS (
    SELECT 1
    FROM [dbo].[PROMOTIONAL_CAMPAIGNS] qc_sd_p
    WHERE qc_sd_p.[ID] = [dbo].[CAMPAIGN_APPLICABILITIES].[CAMPAIGN_ID]
      AND qc_sd_p.[IsDeleted] = 0);

INSERT INTO [dbo].[CAMPAIGN_APPLICABILITIES] (
    [CAMPAIGN_ID],
    [SCOPE],
    [SCOPE_ID]
)
VALUES (
    @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID_ADD,
    @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ADD,
    @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ID_ADD
);