// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.SellerCommissionAssignment;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.SellerCommissionAssignment
{
    public class GetByModelIdQuery : IRequest<Response<List<GetByModelIdResponseDto>>>
    {
        public int SellerCommissionAssignmentCommissionModelId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByModelIdQuery(int sellerCommissionAssignmentCommissionModelId, int? pageNumber, int? pageSize)
        {
            this.SellerCommissionAssignmentCommissionModelId = sellerCommissionAssignmentCommissionModelId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByModelIdHandler : IRequestHandler<GetByModelIdQuery, Response<List<GetByModelIdResponseDto>>>
        {
            private readonly ILogger<GetByModelIdHandler> _logger;
            private readonly ISellerCommissionAssignmentRepository _repository;
            public GetByModelIdHandler(ILogger<GetByModelIdHandler> logger, ISellerCommissionAssignmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByModelIdResponseDto>>> Handle(GetByModelIdQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByModelIdAsync(request.SellerCommissionAssignmentCommissionModelId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}