// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.SellerCommissionAssignment;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.SellerCommissionAssignment
{
    public class UpdateSellerCommissionAssignmentCommand : IRequest<Response<bool>>
    {
        public int SellerId { get; set; }
        public SellerCommissionAssignmentDto request { get; set; }

        public UpdateSellerCommissionAssignmentCommand(int sellerId, SellerCommissionAssignmentDto request)
        {
            this.request = request;
            this.SellerId = sellerId;
        }

        public class UpdateSellerCommissionAssignmentHandler : IRequestHandler<UpdateSellerCommissionAssignmentCommand, Response<bool>>
        {
            private readonly ILogger<UpdateSellerCommissionAssignmentHandler> _logger;
            private readonly ISellerCommissionAssignmentRepository _repository;
            public UpdateSellerCommissionAssignmentHandler(ILogger<UpdateSellerCommissionAssignmentHandler> logger, ISellerCommissionAssignmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdateSellerCommissionAssignmentCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.SellerId);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}