// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CampaignApplicability;
using QuickCode.Demo.PricingEngineModule.Application.Mappings;
using QuickCode.Demo.PricingEngineModule.Persistence.Sql;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Persistence.Repositories
{
    public partial class CampaignApplicabilityRepository : BaseRepository, ICampaignApplicabilityRepository
    {
        public async Task<RepoResponse<List<GetByCampaignIdResponseDto>>> GetByCampaignIdAsync(int campaignApplicabilityCampaignId)
        {
            return await ExecuteWithExceptionHandling(CampaignApplicabilityCrudSqlBindings.OperationNames.GetByCampaignId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CampaignApplicability.Query.GetByCampaignId);
                var parameters = new
                {
                    PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID = campaignApplicabilityCampaignId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var values = await connection.QueryAsync<GetByCampaignIdResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CampaignApplicability");
            });
        }
    }
}