// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionRule;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CommissionRule
{
    public class DeactivateCommand : IRequest<Response<int>>
    {
        public int CommissionRuleId { get; set; }
        public DeactivateRequestDto UpdateRequest { get; set; }

        public DeactivateCommand(int commissionRuleId, DeactivateRequestDto updateRequest)
        {
            this.CommissionRuleId = commissionRuleId;
            this.UpdateRequest = updateRequest;
        }

        public class DeactivateHandler : IRequestHandler<DeactivateCommand, Response<int>>
        {
            private readonly ILogger<DeactivateHandler> _logger;
            private readonly ICommissionRuleRepository _repository;
            public DeactivateHandler(ILogger<DeactivateHandler> logger, ICommissionRuleRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(DeactivateCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.DeactivateAsync(request.CommissionRuleId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}