// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionRule;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CommissionRule
{
    public class InsertCommissionRuleCommand : IRequest<Response<CommissionRuleDto>>
    {
        public CommissionRuleDto request { get; set; }

        public InsertCommissionRuleCommand(CommissionRuleDto request)
        {
            this.request = request;
        }

        public class InsertCommissionRuleHandler : IRequestHandler<InsertCommissionRuleCommand, Response<CommissionRuleDto>>
        {
            private readonly ILogger<InsertCommissionRuleHandler> _logger;
            private readonly ICommissionRuleRepository _repository;
            public InsertCommissionRuleHandler(ILogger<InsertCommissionRuleHandler> logger, ICommissionRuleRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<CommissionRuleDto>> Handle(InsertCommissionRuleCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}