// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionModel;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CommissionModel
{
    public class ListCommissionModelQuery : IRequest<Response<ListResult<CommissionModelDto>>>
    {
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }
        public bool IncludeCount { get; set; }

        public ListCommissionModelQuery(int? pageNumber, int? pageSize, bool includeCount = false)
        {
            this.PageNumber = pageNumber;
            this.PageSize = pageSize;
            this.IncludeCount = includeCount;
        }

        public class ListCommissionModelHandler : IRequestHandler<ListCommissionModelQuery, Response<ListResult<CommissionModelDto>>>
        {
            private readonly ILogger<ListCommissionModelHandler> _logger;
            private readonly ICommissionModelRepository _repository;
            public ListCommissionModelHandler(ILogger<ListCommissionModelHandler> logger, ICommissionModelRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<ListResult<CommissionModelDto>>> Handle(ListCommissionModelQuery request, CancellationToken cancellationToken)
            {
                var listTask = _repository.ListAsync(request.PageNumber, request.PageSize);
                if (!request.IncludeCount)
                    return (await listTask).ToListResultResponse();
                var countTask = _repository.CountAsync();
                await Task.WhenAll(listTask, countTask);
                return (await listTask).ToListResultResponse(await countTask);
            }
        }
    }
}