// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.Order;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Features.Order
{
    public class GetOrdersForSettlementQuery : IRequest<Response<List<GetOrdersForSettlementResponseDto>>>
    {
        public int OrderSellerId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetOrdersForSettlementQuery(int orderSellerId, int? pageNumber, int? pageSize)
        {
            this.OrderSellerId = orderSellerId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetOrdersForSettlementHandler : IRequestHandler<GetOrdersForSettlementQuery, Response<List<GetOrdersForSettlementResponseDto>>>
        {
            private readonly ILogger<GetOrdersForSettlementHandler> _logger;
            private readonly IOrderRepository _repository;
            public GetOrdersForSettlementHandler(ILogger<GetOrdersForSettlementHandler> logger, IOrderRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetOrdersForSettlementResponseDto>>> Handle(GetOrdersForSettlementQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetOrdersForSettlementAsync(request.OrderSellerId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}