// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.ProductCatalogModuleApi.Contracts;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Helpers;

namespace QuickCode.Demo.Portal.Models.ProductCatalogModule
{
    public class CategoryData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public string SelectedKey { get; set; }
        public CategoryDto SelectedItem { get; set; }
        public List<CategoryDto> List { get; set; }
    }

    public static partial class CategoryExtensions
    {
        public static string GetKey(this CategoryDto dto)
        {
            return $"{dto.Id}";
        }

        public static List<string> GetImageColumnNames(this CategoryDto dto) => new()
        {
            "Icon",
            "Banner",
            "IntroVideo"
        };
    }

    public class CategoryGetActiveData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public List<dynamic> List { get; set; } = new();
    }

    public class CategoryGetBySlugData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public string CategorySlug { get; set; }
        public List<dynamic> List { get; set; } = new();
    }

    public class CategoryGetSubCategoriesData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public int CategoryParentCategoryId { get; set; }
        public List<dynamic> List { get; set; } = new();
    }
}