// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.ProductCatalogModuleApi.Contracts;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Helpers;

namespace QuickCode.Demo.Portal.Models.ProductCatalogModule
{
    public class ProductCategoryData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public string SelectedKey { get; set; }
        public ProductCategoryDto SelectedItem { get; set; }
        public List<ProductCategoryDto> List { get; set; }
    }

    public static partial class ProductCategoryExtensions
    {
        public static string GetKey(this ProductCategoryDto dto)
        {
            return $"{dto.ProductId}|{dto.CategoryId}";
        }
    }

    public class ProductCategoryGetByCategoryIdData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public int ProductCategoryCategoryId { get; set; }
        public List<dynamic> List { get; set; } = new();
    }

    public class ProductCategoryGetByProductIdData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public int ProductCategoryProductId { get; set; }
        public List<dynamic> List { get; set; } = new();
    }
}