-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CM.[ID], CM.[MODEL_NAME], CM.[COMMISSION_PERCENTAGE], CM.[IS_ACTIVE] 
FROM [COMMISSION_MODELS] CM 
WHERE CM.[IsDeleted] = 0 
	AND CM.[MODEL_NAME] LIKE '%' + @PRM_COMMISSION_MODEL_MODEL_NAME + '%' 
ORDER BY CM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 