-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CA.[SCOPE], CA.[SCOPE_ID] 
FROM [CAMPAIGN_APPLICABILITIES] CA 
WHERE CA.[CAMPAIGN_ID] = @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID 
ORDER BY CA.[SCOPE], CA.[SCOPE_ID] 