-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[SELLER_BANK_ACCOUNTS] (
    [SELLER_ID],
    [BANK_NAME],
    [ACCOUNT_HOLDER_NAME],
    [IBAN],
    [IS_DEFAULT],
    [IS_VERIFIED]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_SELLER_BANK_ACCOUNT_SELLER_ID,
    @PRM_SELLER_BANK_ACCOUNT_BANK_NAME,
    @PRM_SELLER_BANK_ACCOUNT_ACCOUNT_HOLDER_NAME,
    @PRM_SELLER_BANK_ACCOUNT_IBAN,
    @PRM_SELLER_BANK_ACCOUNT_IS_DEFAULT,
    @PRM_SELLER_BANK_ACCOUNT_IS_VERIFIED
    );