// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Models;
using QuickCode.Demo.Portal.Models.PricingEngineModule;
using QuickCode.Demo.Portal.Helpers;
using QuickCode.Demo.Infrastructure.Integration.Models;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using PricingEngineModuleContracts = QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.PricingEngineModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Demo.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Demo.Portal.Controllers.PricingEngineModule
{
    [Permission("PricingEngineModuleCampaignApplicabilities")]
    [Area("PricingEngineModule")]
    [Route("PricingEngineModuleCampaignApplicabilities")]
    public partial class CampaignApplicabilitiesController : BaseController
    {
        private readonly PricingEngineModuleContracts.ICampaignApplicabilitiesClient pageClient;
        private readonly PricingEngineModuleContracts.IPromotionalCampaignsClient pagePromotionalCampaignClient;
        public CampaignApplicabilitiesController(PricingEngineModuleContracts.ICampaignApplicabilitiesClient pageClient, PricingEngineModuleContracts.IPromotionalCampaignsClient pagePromotionalCampaignClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pagePromotionalCampaignClient = pagePromotionalCampaignClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("ListPartial")]
        [HttpPost]
        public async Task<IActionResult> ListPartial(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return PartialView("_ListTable", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.CampaignApplicabilitiesInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.CampaignApplicabilitiesUpdateAsync(request.CampaignId, request.Scope, request.ScopeId, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.CampaignApplicabilitiesDeleteAsync(request.CampaignId, request.Scope, request.ScopeId);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(CampaignApplicabilityData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(CampaignApplicabilityData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(CampaignApplicabilityData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<CampaignApplicabilityData> PrepareModel()
        {
            var model = GetModel<CampaignApplicabilityData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<CampaignApplicabilityData> PrepareModel(CampaignApplicabilityData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            var result = await pageClient.CampaignApplicabilitiesListAsync(model.CurrentPage, model.PageSize, includeCount: true);
            model.NumberOfRecord = result?.TotalCount ?? 0;
            model.TotalPage = model.PageSize <= 0 ? 0 : (model.NumberOfRecord + model.PageSize - 1) / model.PageSize;
            if (model.TotalPage > 0 && model.CurrentPage > model.TotalPage)
            {
                model.CurrentPage = model.TotalPage;
                result = await pageClient.CampaignApplicabilitiesListAsync(model.CurrentPage, model.PageSize, includeCount: false);
            }

            model.List = result?.Items?.ToList() ?? new();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("PromotionalCampaigns", async () => ToComboItems((await pagePromotionalCampaignClient.PromotionalCampaignsListAsync())?.Items)));
            return comboBoxList;
        }

        [Route("Queries/GetByCampaignId")]
        public async Task<IActionResult> QueryGetByCampaignId()
        {
            var model = GetModel<CampaignApplicabilityGetByCampaignIdData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetByCampaignId", model);
        }

        [Route("Queries/GetByCampaignId")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByCampaignId(CampaignApplicabilityGetByCampaignIdData model)
        {
            model = await PrepareQueryGetByCampaignIdModel(model);
            return View("GetByCampaignId", model);
        }

        [Route("Queries/GetByCampaignIdPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByCampaignIdPartial(CampaignApplicabilityGetByCampaignIdData model)
        {
            model = await PrepareQueryGetByCampaignIdModel(model);
            return PartialView("_GetByCampaignIdTable", model);
        }

        private async Task<CampaignApplicabilityGetByCampaignIdData> PrepareQueryGetByCampaignIdModel(CampaignApplicabilityGetByCampaignIdData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.CampaignApplicabilitiesGetByCampaignIdAsync(model.CampaignApplicabilityCampaignId);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }
    }
}