// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Application.Dtos.SellerPerformanceReview
{
    public record GetBySellerIdResponseDto
    {
        public int Id { get; init; }
        public short Rating { get; init; }
        public string Comment { get; init; }
        public DateTime ReviewDate { get; init; }
    }
}