-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [SELLER_ID],
    [DOCUMENT_TYPE],
    [FILE_URL],
    [STATUS],
    [UPLOADED_DATE],
    [REVIEWED_DATE],
    [REJECTION_REASON]
FROM [dbo].[SELLER_DOCUMENTS]
WHERE [IsDeleted] = 0
ORDER BY
    [ID]
OFFSET @PRM_QC_LIST_OFFSET ROWS
FETCH NEXT @PRM_QC_LIST_PAGE_SIZE ROWS ONLY;