IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS', N'U') AND name = N'IX_RETURN_REQUESTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_RETURN_REQUESTS_IsDeleted] ON [dbo].[RETURN_REQUESTS] ([IsDeleted]);
END