IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ORDER_ITEMS_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.ORDER_ITEMS'))
BEGIN
    ALTER TABLE [dbo].[ORDER_ITEMS] ADD CONSTRAINT [FK_ORDER_ITEMS_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ORDER_STATUS_HISTORIES_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.ORDER_STATUS_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[ORDER_STATUS_HISTORIES] ADD CONSTRAINT [FK_ORDER_STATUS_HISTORIES_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RETURN_REQUESTS_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS'))
BEGIN
    ALTER TABLE [dbo].[RETURN_REQUESTS] ADD CONSTRAINT [FK_RETURN_REQUESTS_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RETURN_REQUESTS_ORDER_ITEMS_ORDER_ITEM_ID' AND parent_object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS'))
BEGIN
    ALTER TABLE [dbo].[RETURN_REQUESTS] ADD CONSTRAINT [FK_RETURN_REQUESTS_ORDER_ITEMS_ORDER_ITEM_ID] FOREIGN KEY ([ORDER_ITEM_ID]) REFERENCES [dbo].[ORDER_ITEMS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_SHIPPING_METHODS_SHIPPING_METHOD_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_SHIPPING_METHODS_SHIPPING_METHOD_ID] FOREIGN KEY ([SHIPPING_METHOD_ID]) REFERENCES [dbo].[SHIPPING_METHODS] ([ID]);
END