IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS', N'U') AND name = N'IX_RETURN_REQUESTS_ORDER_ID')
BEGIN
    CREATE INDEX [IX_RETURN_REQUESTS_ORDER_ID] ON [dbo].[RETURN_REQUESTS] ([ORDER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS', N'U') AND name = N'IX_RETURN_REQUESTS_ORDER_ITEM_ID')
BEGIN
    CREATE INDEX [IX_RETURN_REQUESTS_ORDER_ITEM_ID] ON [dbo].[RETURN_REQUESTS] ([ORDER_ITEM_ID]);
END