IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDER_ITEMS', N'U') AND name = N'IX_ORDER_ITEMS_ORDER_ID')
BEGIN
    CREATE INDEX [IX_ORDER_ITEMS_ORDER_ID] ON [dbo].[ORDER_ITEMS] ([ORDER_ID]);
END