IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDER_STATUS_MANAGERS', N'U') AND name = N'IX_ORDER_STATUS_MANAGERS_IsDeleted')
BEGIN
    CREATE INDEX [IX_ORDER_STATUS_MANAGERS_IsDeleted] ON [dbo].[ORDER_STATUS_MANAGERS] ([IsDeleted]);
END