IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDER_STATUS_HISTORIES', N'U') AND name = N'IX_ORDER_STATUS_HISTORIES_ORDER_ID')
BEGIN
    CREATE INDEX [IX_ORDER_STATUS_HISTORIES_ORDER_ID] ON [dbo].[ORDER_STATUS_HISTORIES] ([ORDER_ID]);
END