IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SHIPMENTS_SHIPPING_METHODS_SHIPPING_METHOD_ID' AND parent_object_id = OBJECT_ID(N'dbo.SHIPMENTS'))
BEGIN
    ALTER TABLE [dbo].[SHIPMENTS] ADD CONSTRAINT [FK_SHIPMENTS_SHIPPING_METHODS_SHIPPING_METHOD_ID] FOREIGN KEY ([SHIPPING_METHOD_ID]) REFERENCES [dbo].[SHIPPING_METHODS] ([ID]);
END