IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_ORDER_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_ORDER_ID] ON [dbo].[SHIPMENTS] ([ORDER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_SHIPPING_METHOD_ID')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_SHIPPING_METHOD_ID] ON [dbo].[SHIPMENTS] ([SHIPPING_METHOD_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPMENTS', N'U') AND name = N'IX_SHIPMENTS_TRACKING_NUMBER')
BEGIN
    CREATE INDEX [IX_SHIPMENTS_TRACKING_NUMBER] ON [dbo].[SHIPMENTS] ([TRACKING_NUMBER]);
END