IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SHIPPING_METHODS', N'U') AND name = N'IX_SHIPPING_METHODS_IsDeleted')
BEGIN
    CREATE INDEX [IX_SHIPPING_METHODS_IsDeleted] ON [dbo].[SHIPPING_METHODS] ([IsDeleted]);
END