IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RETURN_REQUESTS_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS'))
BEGIN
    ALTER TABLE [dbo].[RETURN_REQUESTS] ADD CONSTRAINT [FK_RETURN_REQUESTS_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_RETURN_REQUESTS_ORDER_ITEMS_ORDER_ITEM_ID' AND parent_object_id = OBJECT_ID(N'dbo.RETURN_REQUESTS'))
BEGIN
    ALTER TABLE [dbo].[RETURN_REQUESTS] ADD CONSTRAINT [FK_RETURN_REQUESTS_ORDER_ITEMS_ORDER_ITEM_ID] FOREIGN KEY ([ORDER_ITEM_ID]) REFERENCES [dbo].[ORDER_ITEMS] ([ID]);
END