IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDERS', N'U') AND name = N'IX_ORDERS_CUSTOMER_ID')
BEGIN
    CREATE INDEX [IX_ORDERS_CUSTOMER_ID] ON [dbo].[ORDERS] ([CUSTOMER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDERS', N'U') AND name = N'IX_ORDERS_ORDER_NUMBER')
BEGIN
    CREATE INDEX [IX_ORDERS_ORDER_NUMBER] ON [dbo].[ORDERS] ([ORDER_NUMBER]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDERS', N'U') AND name = N'IX_ORDERS_SELLER_ID_ORDER_DATE')
BEGIN
    CREATE INDEX [IX_ORDERS_SELLER_ID_ORDER_DATE] ON [dbo].[ORDERS] ([SELLER_ID], [ORDER_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDERS', N'U') AND name = N'IX_ORDERS_SELLER_ID_STATUS')
BEGIN
    CREATE INDEX [IX_ORDERS_SELLER_ID_STATUS] ON [dbo].[ORDERS] ([SELLER_ID], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ORDERS', N'U') AND name = N'IX_ORDERS_STATUS')
BEGIN
    CREATE INDEX [IX_ORDERS_STATUS] ON [dbo].[ORDERS] ([STATUS]);
END