IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ORDER_STATUS_HISTORIES_ORDERS_ORDER_ID' AND parent_object_id = OBJECT_ID(N'dbo.ORDER_STATUS_HISTORIES'))
BEGIN
    ALTER TABLE [dbo].[ORDER_STATUS_HISTORIES] ADD CONSTRAINT [FK_ORDER_STATUS_HISTORIES_ORDERS_ORDER_ID] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[ORDERS] ([ID]);
END