// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.AttributeDefinition;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Services.AttributeDefinition
{
    public partial class AttributeDefinitionService : IAttributeDefinitionService
    {
        private readonly ILogger<AttributeDefinitionService> _logger;
        private readonly IAttributeDefinitionRepository _repository;
        public AttributeDefinitionService(ILogger<AttributeDefinitionService> logger, IAttributeDefinitionRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<Response<AttributeDefinitionDto>> InsertAsync(AttributeDefinitionDto request)
        {
            var returnValue = await _repository.InsertAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteAsync(AttributeDefinitionDto request)
        {
            var returnValue = await _repository.DeleteAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> UpdateAsync(int id, AttributeDefinitionDto request)
        {
            var updateItem = await _repository.GetByPkAsync(request.Id);
            if (updateItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.UpdateAsync(request);
            return returnValue.ToResponse();
        }

        public async Task<Response<ListResult<AttributeDefinitionDto>>> ListAsync(int? pageNumber, int? pageSize, bool includeCount = false)
        {
            var listTask = _repository.ListAsync(pageNumber, pageSize);
            if (!includeCount)
                return (await listTask).ToListResultResponse();
            var countTask = _repository.CountAsync();
            await Task.WhenAll(listTask, countTask);
            return (await listTask).ToListResultResponse(await countTask);
        }

        public async Task<Response<AttributeDefinitionDto>> GetItemAsync(int id)
        {
            var returnValue = await _repository.GetByPkAsync(id);
            return returnValue.ToResponse();
        }

        public async Task<Response<bool>> DeleteItemAsync(int id)
        {
            var deleteItem = await _repository.GetByPkAsync(id);
            if (deleteItem.Code == 404)
                return Response<bool>.NotFound();
            var returnValue = await _repository.DeleteAsync(deleteItem.Value);
            return returnValue.ToResponse();
        }

        public async Task<Response<int>> TotalItemCountAsync()
        {
            var returnValue = await _repository.CountAsync();
            return returnValue.ToResponse();
        }

        public async Task<Response<GetByCodeResponseDto>> GetByCodeAsync(string attributeDefinitionCode)
        {
            var returnValue = await _repository.GetByCodeAsync(attributeDefinitionCode);
            return returnValue.ToResponse();
        }
    }
}