// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.PayoutPeriod;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.PayoutPeriod
{
    public class GetItemPayoutPeriodQuery : IRequest<Response<PayoutPeriodDto>>
    {
        public int Id { get; set; }

        public GetItemPayoutPeriodQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemPayoutPeriodHandler : IRequestHandler<GetItemPayoutPeriodQuery, Response<PayoutPeriodDto>>
        {
            private readonly ILogger<GetItemPayoutPeriodHandler> _logger;
            private readonly IPayoutPeriodRepository _repository;
            public GetItemPayoutPeriodHandler(ILogger<GetItemPayoutPeriodHandler> logger, IPayoutPeriodRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<PayoutPeriodDto>> Handle(GetItemPayoutPeriodQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}