-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 CM.[ID], CM.[IS_ACTIVE] 
FROM [COMMISSION_MODELS] CM 
WHERE CM.[IsDeleted] = 0 
	AND CM.[NAME] = @PRM_COMMISSION_MODEL_NAME 
ORDER BY CM.[ID] 