-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [FINANCIAL_ADJUSTMENTS] 
	SET [APPROVED_BY_USER_ID] = @FINANCIAL_ADJUSTMENT_APPROVED_BY_USER_ID, [APPROVED_DATE] = GETDATE() 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_FINANCIAL_ADJUSTMENT_ID