-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 SUM(O.[TOTAL_AMOUNT]) AS TOTAL_REVENUE,
	COUNT(*) AS ORDER_COUNT 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[SELLER_ID] = @PRM_ORDER_SELLER_ID 
	AND O.[ORDER_DATE] > DATEADD(DAY, -30,
	GETDATE()) 