-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT OI.[ID], OI.[PRODUCT_NAME], OI.[SKU], OI.[QUANTITY], OI.[UNIT_PRICE], OI.[TOTAL_PRICE] 
FROM [ORDER_ITEMS] OI 
WHERE OI.[IsDeleted] = 0 
	AND OI.[ORDER_ID] = @PRM_ORDER_ITEM_ORDER_ID 
ORDER BY OI.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 