// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Application.Mappings;
using QuickCode.Demo.FinanceSettlementModule.Persistence.Sql;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Persistence.Repositories
{
    public partial class SellerPayoutRepository : BaseRepository, ISellerPayoutRepository
    {
        public async Task<RepoResponse<List<GetBySellerIdResponseDto>>> GetBySellerIdAsync(int sellerPayoutSellerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetBySellerId, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetBySellerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetBySellerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SELLER_PAYOUT_SELLER_ID = sellerPayoutSellerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetBySellerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(PayoutStatus sellerPayoutStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetByStatus, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SELLER_PAYOUT_STATUS = sellerPayoutStatus.ToString(),
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }

        public async Task<RepoResponse<List<GetWithPeriodResponseDto>>> GetWithPeriodAsync(int sellerPayoutsPayoutPeriodId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetWithPeriod, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetWithPeriodResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetWithPeriod);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SELLER_PAYOUTS_PAYOUT_PERIOD_ID = sellerPayoutsPayoutPeriodId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetWithPeriodResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }

        public async Task<RepoResponse<List<GetPendingPayoutsResponseDto>>> GetPendingPayoutsAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetPendingPayouts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPendingPayoutsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetPendingPayouts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetPendingPayoutsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }

        public async Task<RepoResponse<GetPendingPayoutsSummaryResponseDto>> GetPendingPayoutsSummaryAsync()
        {
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetPendingPayoutsSummary, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetPendingPayoutsSummary);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetPendingPayoutsSummaryResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in SellerPayout");
            });
        }

        public async Task<RepoResponse<List<GetApprovedPayoutsResponseDto>>> GetApprovedPayoutsAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetApprovedPayouts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetApprovedPayoutsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetApprovedPayouts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetApprovedPayoutsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }

        public async Task<RepoResponse<GetPaidSummaryResponseDto>> GetPaidSummaryAsync()
        {
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetPaidSummary, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetPaidSummary);
                var parameters = new
                {
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetPaidSummaryResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in SellerPayout");
            });
        }

        public async Task<RepoResponse<List<GetFailedPayoutsResponseDto>>> GetFailedPayoutsAsync(int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetFailedPayouts, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetFailedPayoutsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetFailedPayouts);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetFailedPayoutsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }

        public async Task<RepoResponse<List<GetByPeriodResponseDto>>> GetByPeriodAsync(int sellerPayoutPayoutPeriodId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerPayoutCrudSqlBindings.OperationNames.GetByPeriod, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByPeriodResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerPayout.Query.GetByPeriod);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SELLER_PAYOUT_PAYOUT_PERIOD_ID = sellerPayoutPayoutPeriodId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetByPeriodResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerPayout");
                }
            });
        }
    }
}