// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Dtos.TransactionLedger
{
    public record GetBySellerIdResponseDto
    {
        public int Id { get; init; }
        public TransactionType TransactionType { get; init; }
        public decimal Amount { get; init; }
        public string Description { get; init; }
        public DateTime TransactionDate { get; init; }
    }
}