-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT CR.[ID], CR.[RULE_NAME], CR.[MIN_ORDER_VALUE], CR.[MAX_ORDER_VALUE], CR.[OVERRIDE_PERCENTAGE] 
FROM [COMMISSION_RULES] CR 
WHERE CR.[IsDeleted] = 0 
	AND CR.[COMMISSION_MODEL_ID] = @PRM_COMMISSION_RULE_COMMISSION_MODEL_ID 
ORDER BY CR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 