// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QcEntity = global::QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.OrderItem;
using QuickCode.Demo.OrderManagementModule.Application.Mappings;
using QuickCode.Demo.OrderManagementModule.Persistence.Sql;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Persistence.Repositories
{
    public partial class OrderItemRepository : BaseRepository, IOrderItemRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public OrderItemRepository(ILogger<OrderItemRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "OrderItem")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<OrderItemDto>> InsertAsync(OrderItemDto value)
        {
            return await ExecuteWithExceptionHandling(OrderItemCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OrderItem.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(OrderItemCrudSqlBindings.ParameterNamePrefix, value, OrderItemCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.OrderItem>(sql, p);
                return new RepoResponse<OrderItemDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(OrderItemDto value)
        {
            return await ExecuteWithExceptionHandling(OrderItemCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OrderItem.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(OrderItemCrudSqlBindings.ParameterNamePrefix, value, OrderItemCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(OrderItemDto value)
        {
            return await ExecuteWithExceptionHandling(OrderItemCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OrderItem.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(OrderItemCrudSqlBindings.ParameterNamePrefix, value, OrderItemCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<OrderItemDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(OrderItemCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OrderItem.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(OrderItemCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.OrderItem>(sql, p);
                return row == null ? CreateNotFoundResponse<OrderItemDto>("Not found in OrderItem") : new RepoResponse<OrderItemDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<OrderItemDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(OrderItemCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<OrderItemDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.OrderItem.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.OrderItem>(sql, p);
                return new RepoResponse<List<OrderItemDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(OrderItemCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.OrderItem.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}