// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Brand;

namespace QuickCode.Demo.ProductCatalogModule.Persistence.Repositories;
internal static class BrandCrudSqlBindings
{
    public const string StoreTableName = "BRANDS";
    public const string ParameterNamePrefix = "BRAND";
    public const string IdParameterName = "PRM_BRAND_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string SearchByName = "SearchByName";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("NAME", nameof(BrandDto.Name)),
        ("LOGO", nameof(BrandDto.Logo)),
        ("PHOTO", nameof(BrandDto.Photo)),
        ("BRAND_VIDEO", nameof(BrandDto.BrandVideo)),
        ("CATALOG_PDF", nameof(BrandDto.CatalogPdf)),
        ("IS_ACTIVE", nameof(BrandDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("NAME", nameof(BrandDto.Name)),
        ("LOGO", nameof(BrandDto.Logo)),
        ("PHOTO", nameof(BrandDto.Photo)),
        ("BRAND_VIDEO", nameof(BrandDto.BrandVideo)),
        ("CATALOG_PDF", nameof(BrandDto.CatalogPdf)),
        ("IS_ACTIVE", nameof(BrandDto.IsActive)),
        ("ID", nameof(BrandDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(BrandDto.Id))
    };
}