// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

public enum PayoutStatus{
	[Description("Payout calculated and awaiting approval")]
	Pending,
	[Description("Payout approved and ready for processing")]
	Approved,
	[Description("Payout approved and sent to payment provider")]
	Processing,
	[Description("Payout successfully transferred to the seller")]
	Paid,
	[Description("Payout transfer failed")]
	Failed,
	[Description("Payout cancelled by admin")]
	Cancelled
}
