// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionRule;
using System.Threading.Tasks;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories
{
    public partial interface ICommissionRuleRepository : IBaseRepository<CommissionRuleDto>
    {
        Task<RepoResponse<CommissionRuleDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByModelIdResponseDto>>> GetByModelIdAsync(int commissionRuleCommissionModelId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetActiveRulesResponseDto>>> GetActiveRulesAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByValueRangeResponseDto>>> GetByValueRangeAsync(decimal commissionRuleMinOrderValue, decimal commissionRuleMaxOrderValue, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> DeactivateAsync(int commissionRuleId, DeactivateRequestDto updateRequest);
        Task<RepoResponse<int>> UpdateRuleAsync(int commissionRuleId, UpdateRuleRequestDto updateRequest);
    }
}