// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.FinancialAdjustment;
using System.Threading.Tasks;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories
{
    public partial interface IFinancialAdjustmentRepository : IBaseRepository<FinancialAdjustmentDto>
    {
        Task<RepoResponse<FinancialAdjustmentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetBySellerIdResponseDto>>> GetBySellerIdAsync(int financialAdjustmentSellerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByReasonResponseDto>>> GetByReasonAsync(AdjustmentReason financialAdjustmentReason, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetTotalBySellerResponseDto>> GetTotalBySellerAsync(int financialAdjustmentSellerId);
        Task<RepoResponse<List<GetRecentAdjustmentsResponseDto>>> GetRecentAdjustmentsAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(int financialAdjustmentApprovedByUserId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByPayoutResponseDto>>> GetByPayoutAsync(int financialAdjustmentPayoutId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetActiveAdjustmentsResponseDto>>> GetActiveAdjustmentsAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> ApproveAsync(int financialAdjustmentId, ApproveRequestDto updateRequest);
        Task<RepoResponse<int>> DeactivateAsync(int financialAdjustmentId, DeactivateRequestDto updateRequest);
    }
}