// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.TransactionLedger;
using System.Threading.Tasks;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories
{
    public partial interface ITransactionLedgerRepository : IBaseRepository<TransactionLedgerDto>
    {
        Task<RepoResponse<TransactionLedgerDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetBySellerIdResponseDto>>> GetBySellerIdAsync(int transactionLedgerSellerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(TransactionType transactionLedgerTransactionType, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetSellerBalanceResponseDto>> GetSellerBalanceAsync(int transactionLedgerSellerId);
        Task<RepoResponse<List<GetTransactionsByDateRangeResponseDto>>> GetTransactionsByDateRangeAsync(int transactionLedgerSellerId, DateTime transactionLedgerTransactionDateFrom, DateTime transactionLedgerTransactionDateTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecentTransactionsResponseDto>>> GetRecentTransactionsAsync(int transactionLedgerSellerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetDailySummaryResponseDto>> GetDailySummaryAsync(int transactionLedgerSellerId);
        Task<RepoResponse<List<GetByReferenceResponseDto>>> GetByReferenceAsync(string transactionLedgerReferenceId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetSalesTotalResponseDto>> GetSalesTotalAsync(int transactionLedgerSellerId);
        Task<RepoResponse<GetRefundsTotalResponseDto>> GetRefundsTotalAsync(int transactionLedgerSellerId);
        Task<RepoResponse<int>> AddTransactionAsync(int transactionLedgerId, AddTransactionRequestDto updateRequest);
    }
}