// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.SellerManagementModule.Domain.Entities;
using QuickCode.Demo.SellerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.SellerManagementModule.Application.Dtos.SellerBankAccount;
using QuickCode.Demo.SellerManagementModule.Application.Mappings;
using QuickCode.Demo.SellerManagementModule.Persistence.Sql;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Persistence.Repositories
{
    public partial class SellerBankAccountRepository : BaseRepository, ISellerBankAccountRepository
    {
        public async Task<RepoResponse<List<GetBySellerIdResponseDto>>> GetBySellerIdAsync(int sellerBankAccountSellerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling(SellerBankAccountCrudSqlBindings.OperationNames.GetBySellerId, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetBySellerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.SellerBankAccount.Query.GetBySellerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_SELLER_BANK_ACCOUNT_SELLER_ID = sellerBankAccountSellerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                    var values = await connection.QueryAsync<GetBySellerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in SellerBankAccount");
                }
            });
        }

        public async Task<RepoResponse<GetDefaultBySellerIdResponseDto>> GetDefaultBySellerIdAsync(int sellerBankAccountSellerId)
        {
            return await ExecuteWithExceptionHandling(SellerBankAccountCrudSqlBindings.OperationNames.GetDefaultBySellerId, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerBankAccount.Query.GetDefaultBySellerId);
                var parameters = new
                {
                    PRM_SELLER_BANK_ACCOUNT_SELLER_ID = sellerBankAccountSellerId
                };
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var value = await connection.QueryFirstOrDefaultAsync<GetDefaultBySellerIdResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in SellerBankAccount");
            });
        }
    }
}