// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Demo.ProductCatalogModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class Brand
    {
        public static class Query
        {
            private const string _prefix = "ProductCatalogModule.Brand.Query";
            private const string _sqlScriptStem = "Brand";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActive => ResourceKey($"{_sqlScriptStem}.GetActive.g.sql");
            public static string SearchByName => ResourceKey($"{_sqlScriptStem}.SearchByName.g.sql");
        }
    }
}