// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.TransactionLedger;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.TransactionLedger
{
    public class GetByReferenceQuery : IRequest<Response<List<GetByReferenceResponseDto>>>
    {
        public string TransactionLedgerReferenceId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByReferenceQuery(string transactionLedgerReferenceId, int? pageNumber, int? pageSize)
        {
            this.TransactionLedgerReferenceId = transactionLedgerReferenceId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByReferenceHandler : IRequestHandler<GetByReferenceQuery, Response<List<GetByReferenceResponseDto>>>
        {
            private readonly ILogger<GetByReferenceHandler> _logger;
            private readonly ITransactionLedgerRepository _repository;
            public GetByReferenceHandler(ILogger<GetByReferenceHandler> logger, ITransactionLedgerRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByReferenceResponseDto>>> Handle(GetByReferenceQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByReferenceAsync(request.TransactionLedgerReferenceId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}