// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.TransactionLedger;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.TransactionLedger
{
    public class GetDailySummaryQuery : IRequest<Response<GetDailySummaryResponseDto>>
    {
        public int TransactionLedgerSellerId { get; set; }

        public GetDailySummaryQuery(int transactionLedgerSellerId)
        {
            this.TransactionLedgerSellerId = transactionLedgerSellerId;
        }

        public class GetDailySummaryHandler : IRequestHandler<GetDailySummaryQuery, Response<GetDailySummaryResponseDto>>
        {
            private readonly ILogger<GetDailySummaryHandler> _logger;
            private readonly ITransactionLedgerRepository _repository;
            public GetDailySummaryHandler(ILogger<GetDailySummaryHandler> logger, ITransactionLedgerRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<GetDailySummaryResponseDto>> Handle(GetDailySummaryQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetDailySummaryAsync(request.TransactionLedgerSellerId);
                return returnValue.ToResponse();
            }
        }
    }
}