// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.TransactionLedger;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.TransactionLedger
{
    public class GetItemTransactionLedgerQuery : IRequest<Response<TransactionLedgerDto>>
    {
        public int Id { get; set; }

        public GetItemTransactionLedgerQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemTransactionLedgerHandler : IRequestHandler<GetItemTransactionLedgerQuery, Response<TransactionLedgerDto>>
        {
            private readonly ILogger<GetItemTransactionLedgerHandler> _logger;
            private readonly ITransactionLedgerRepository _repository;
            public GetItemTransactionLedgerHandler(ILogger<GetItemTransactionLedgerHandler> logger, ITransactionLedgerRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<TransactionLedgerDto>> Handle(GetItemTransactionLedgerQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}