// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QcEntity = global::QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionEntry;
using QuickCode.Demo.FinanceSettlementModule.Application.Mappings;
using QuickCode.Demo.FinanceSettlementModule.Persistence.Sql;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Persistence.Repositories
{
    public partial class CommissionEntryRepository : BaseRepository, ICommissionEntryRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CommissionEntryRepository(ILogger<CommissionEntryRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CommissionEntry")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CommissionEntryDto>> InsertAsync(CommissionEntryDto value)
        {
            return await ExecuteWithExceptionHandling(CommissionEntryCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionEntry.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CommissionEntryCrudSqlBindings.ParameterNamePrefix, value, CommissionEntryCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CommissionEntry>(sql, p);
                return new RepoResponse<CommissionEntryDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CommissionEntryDto value)
        {
            return await ExecuteWithExceptionHandling(CommissionEntryCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionEntry.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CommissionEntryCrudSqlBindings.ParameterNamePrefix, value, CommissionEntryCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CommissionEntryDto value)
        {
            return await ExecuteWithExceptionHandling(CommissionEntryCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionEntry.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CommissionEntryCrudSqlBindings.ParameterNamePrefix, value, CommissionEntryCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CommissionEntryDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CommissionEntryCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionEntry.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CommissionEntryCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CommissionEntry>(sql, p);
                return row == null ? CreateNotFoundResponse<CommissionEntryDto>("Not found in CommissionEntry") : new RepoResponse<CommissionEntryDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CommissionEntryDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CommissionEntryCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CommissionEntryDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CommissionEntry.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CommissionEntry>(sql, p);
                return new RepoResponse<List<CommissionEntryDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CommissionEntryCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CommissionEntry.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}