// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Demo.FinanceSettlementModule.Domain;
using QuickCode.Demo.Domain.Shared.Abstractions;
using QuickCode.Demo.Domain.Shared.Entities;

namespace QuickCode.Demo.FinanceSettlementModule.Domain.Entities;

[Table("PAYOUT_PERIODS")]
public partial class PayoutPeriod : BaseSoftDeletable, IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("ID")]
	public int Id { get; set; }
	
	[Column("PERIOD_NAME")]
	[StringLength(50)]
	public string PeriodName { get; set; }
	
	[Column("START_DATE")]
	public DateTime StartDate { get; set; }
	
	[Column("END_DATE")]
	public DateTime EndDate { get; set; }
	
	[Column("IS_CLOSED")]
	public bool IsClosed { get; set; }
	
	[Column("CLOSED_DATE")]
	public DateTime ClosedDate { get; set; }
	
	[Column("CREATED_DATE")]
	public DateTime CreatedDate { get; set; }
	
	[InverseProperty(nameof(SellerPayout.PayoutPeriod))]
	public virtual ICollection<SellerPayout> SellerPayouts { get; } = new List<SellerPayout>();

	[InverseProperty(nameof(PayoutReport.PayoutPeriod))]
	public virtual ICollection<PayoutReport> PayoutReports { get; } = new List<PayoutReport>();
}

