// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QcEntity = global::QuickCode.Demo.SellerManagementModule.Domain.Entities;
using QuickCode.Demo.SellerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.SellerManagementModule.Application.Dtos.Seller;
using QuickCode.Demo.SellerManagementModule.Application.Mappings;
using QuickCode.Demo.SellerManagementModule.Persistence.Sql;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Persistence.Repositories
{
    public partial class SellerRepository : BaseRepository, ISellerRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public SellerRepository(ILogger<SellerRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "Seller")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<SellerDto>> InsertAsync(SellerDto value)
        {
            return await ExecuteWithExceptionHandling(SellerCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Seller.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(SellerCrudSqlBindings.ParameterNamePrefix, value, SellerCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.Seller>(sql, p);
                return new RepoResponse<SellerDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(SellerDto value)
        {
            return await ExecuteWithExceptionHandling(SellerCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Seller.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(SellerCrudSqlBindings.ParameterNamePrefix, value, SellerCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(SellerDto value)
        {
            return await ExecuteWithExceptionHandling(SellerCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Seller.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(SellerCrudSqlBindings.ParameterNamePrefix, value, SellerCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<SellerDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(SellerCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Seller.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(SellerCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.Seller>(sql, p);
                return row == null ? CreateNotFoundResponse<SellerDto>("Not found in Seller") : new RepoResponse<SellerDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<SellerDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(SellerCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SellerDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.Seller.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.Seller>(sql, p);
                return new RepoResponse<List<SellerDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(SellerCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Seller.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}