// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Web.Controllers;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CategoryCommissionOverride;
using QuickCode.Demo.PricingEngineModule.Application.Features.CategoryCommissionOverride;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Api.Controllers
{
    public partial class CategoryCommissionOverridesController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<CategoryCommissionOverridesController> logger;
        private readonly IServiceProvider serviceProvider;
        public CategoryCommissionOverridesController(IMediator mediator, IServiceProvider serviceProvider, ILogger<CategoryCommissionOverridesController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListResult<CategoryCommissionOverrideDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size, [FromQuery] bool includeCount = false)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListCategoryCommissionOverrideQuery(page, size, includeCount));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountCategoryCommissionOverrideQuery());
            if (HandleResponseError(response, logger, "CategoryCommissionOverride") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(CategoryCommissionOverrideDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemCategoryCommissionOverrideQuery(id));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(CategoryCommissionOverrideDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(CategoryCommissionOverrideDto model)
        {
            var response = await mediator.Send(new InsertCategoryCommissionOverrideCommand(model));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, CategoryCommissionOverrideDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdateCategoryCommissionOverrideCommand(id, model));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemCategoryCommissionOverrideCommand(id));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-by-category-id/{categoryCommissionOverrideCategoryId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(GetByCategoryIdResponseDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetByCategoryIdAsync(int categoryCommissionOverrideCategoryId)
        {
            var response = await mediator.Send(new GetByCategoryIdQuery(categoryCommissionOverrideCategoryId));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride", $"CategoryCommissionOverrideCategoryId: '{categoryCommissionOverrideCategoryId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("remove-override/{categoryCommissionOverrideId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> RemoveOverrideAsync(int categoryCommissionOverrideId)
        {
            var response = await mediator.Send(new RemoveOverrideCommand(categoryCommissionOverrideId));
            if (HandleResponseError(response, logger, "CategoryCommissionOverride", $"CategoryCommissionOverrideId: '{categoryCommissionOverrideId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}