// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Application.Contracts.Mediator;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Web.Controllers;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.PromotionalCampaign;
using QuickCode.Demo.PricingEngineModule.Application.Features.PromotionalCampaign;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Api.Controllers
{
    public partial class PromotionalCampaignsController : QuickCodeBaseApiController
    {
        private readonly IMediator mediator;
        private readonly ILogger<PromotionalCampaignsController> logger;
        private readonly IServiceProvider serviceProvider;
        public PromotionalCampaignsController(IMediator mediator, IServiceProvider serviceProvider, ILogger<PromotionalCampaignsController> logger)
        {
            this.mediator = mediator;
            this.logger = logger;
            this.serviceProvider = serviceProvider;
        }

        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ListResult<PromotionalCampaignDto>))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> ListAsync([FromQuery] int? page, int? size, [FromQuery] bool includeCount = false)
        {
            if (ValidatePagination(page, size) is {} error)
                return error;
            var response = await mediator.Send(new ListPromotionalCampaignQuery(page, size, includeCount));
            if (HandleResponseError(response, logger, "PromotionalCampaign", "List") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("count")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> CountAsync()
        {
            var response = await mediator.Send(new TotalCountPromotionalCampaignQuery());
            if (HandleResponseError(response, logger, "PromotionalCampaign") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(PromotionalCampaignDto))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetItemAsync(int id)
        {
            var response = await mediator.Send(new GetItemPromotionalCampaignQuery(id));
            if (HandleResponseError(response, logger, "PromotionalCampaign", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created, Type = typeof(PromotionalCampaignDto))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> InsertAsync(PromotionalCampaignDto model)
        {
            var response = await mediator.Send(new InsertPromotionalCampaignCommand(model));
            if (HandleResponseError(response, logger, "PromotionalCampaign") is {} responseError)
                return responseError;
            return CreatedAtRoute(new { id = response.Value.Id }, response.Value);
        }

        [HttpPut("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> UpdateAsync(int id, PromotionalCampaignDto model)
        {
            if (!(model.Id == id))
            {
                return BadRequest($"Id: '{id}' must be equal to model.Id: '{model.Id}'");
            }

            var response = await mediator.Send(new UpdatePromotionalCampaignCommand(id, model));
            if (HandleResponseError(response, logger, "PromotionalCampaign", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpDelete("{id:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(bool))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var response = await mediator.Send(new DeleteItemPromotionalCampaignCommand(id));
            if (HandleResponseError(response, logger, "PromotionalCampaign", $"Id: '{id}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-active-campaigns")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetActiveCampaignsResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetActiveCampaignsAsync(int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetActiveCampaignsQuery(pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PromotionalCampaign", $"") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpGet("get-campaigns-in-date-range/{promotionalCampaignStartDateFrom:datetime}/{promotionalCampaignStartDateTo:datetime}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<GetCampaignsInDateRangeResponseDto>))]
        [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(string))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> GetCampaignsInDateRangeAsync(DateTime promotionalCampaignStartDateFrom, DateTime promotionalCampaignStartDateTo, int? pageNumber, int? pageSize)
        {
            if (pageNumber < 1)
            {
                var pageNumberError = $"Page Number must be greater than 1";
                logger.LogWarning($"List Error: '{pageNumberError}''");
                return NotFound(pageNumberError);
            }

            var response = await mediator.Send(new GetCampaignsInDateRangeQuery(promotionalCampaignStartDateFrom, promotionalCampaignStartDateTo, pageNumber, pageSize));
            if (HandleResponseError(response, logger, "PromotionalCampaign", $"PromotionalCampaignStartDateFrom: '{promotionalCampaignStartDateFrom}', PromotionalCampaignStartDateTo: '{promotionalCampaignStartDateTo}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }

        [HttpPatch("deactivate/{promotionalCampaignId:int}")]
        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(int))]
        [ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
        public async Task<IActionResult> DeactivateAsync(int promotionalCampaignId, [FromBody] DeactivateRequestDto updateRequest)
        {
            var response = await mediator.Send(new DeactivateCommand(promotionalCampaignId, updateRequest));
            if (HandleResponseError(response, logger, "PromotionalCampaign", $"PromotionalCampaignId: '{promotionalCampaignId}'") is {} responseError)
                return responseError;
            return Ok(response.Value);
        }
    }
}