// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Demo.PricingEngineModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class PromotionalCampaign
    {
        public static class Query
        {
            private const string _prefix = "PricingEngineModule.PromotionalCampaign.Query";
            private const string _sqlScriptStem = "PromotionalCampaign";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetActiveCampaigns => ResourceKey($"{_sqlScriptStem}.GetActiveCampaigns.g.sql");
            public static string GetCampaignsInDateRange => ResourceKey($"{_sqlScriptStem}.GetCampaignsInDateRange.g.sql");
        }
    }
}