-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT R.[ID], R.[ORDER_ID], R.[REASON], R.[REQUESTED_DATE] 
FROM [RETURN_REQUESTS] R 
	INNER JOIN [ORDERS] O 
			ON R.[ORDER_ID] = O.[ID] 
WHERE R.[IsDeleted] = 0 
	AND O.[IsDeleted] = 0 
	AND O.[SELLER_ID] = @PRM_ORDERS_SELLER_ID 
	AND R.[STATUS] = 'Requested' 
ORDER BY R.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 