// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.SellerManagementModule.Application.Dtos.Seller;
using SellerEntity = QuickCode.Demo.SellerManagementModule.Domain.Entities.Seller;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Application.Mappings
{
    public static class SellerMappings
    {
        public static List<SellerDto> ToDto(this IEnumerable<SellerEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static SellerDto ToDto(this SellerEntity model)
        {
            return new SellerDto
            {
                Id = model.Id,
                UserId = model.UserId,
                CompanyName = model.CompanyName,
                ContactEmail = model.ContactEmail,
                ContactPhone = model.ContactPhone,
                Status = model.Status,
                SellerTierId = model.SellerTierId,
                JoinedDate = model.JoinedDate
            };
        }

        public static SellerEntity ToEntity(this SellerDto model)
        {
            return new SellerEntity
            {
                Id = model.Id,
                UserId = model.UserId,
                CompanyName = model.CompanyName,
                ContactEmail = model.ContactEmail,
                ContactPhone = model.ContactPhone,
                Status = model.Status,
                SellerTierId = model.SellerTierId,
                JoinedDate = model.JoinedDate
            };
        }
    }
}