// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.SellerManagementModule.Application.Dtos.Store;
using StoreEntity = QuickCode.Demo.SellerManagementModule.Domain.Entities.Store;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Application.Mappings
{
    public static class StoreMappings
    {
        public static List<StoreDto> ToDto(this IEnumerable<StoreEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static StoreDto ToDto(this StoreEntity model)
        {
            return new StoreDto
            {
                Id = model.Id,
                SellerId = model.SellerId,
                Name = model.Name,
                Slug = model.Slug,
                Description = model.Description,
                LogoUrl = model.LogoUrl,
                IsActive = model.IsActive
            };
        }

        public static StoreEntity ToEntity(this StoreDto model)
        {
            return new StoreEntity
            {
                Id = model.Id,
                SellerId = model.SellerId,
                Name = model.Name,
                Slug = model.Slug,
                Description = model.Description,
                LogoUrl = model.LogoUrl,
                IsActive = model.IsActive
            };
        }
    }
}