-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT PR.[ID], PR.[TOTAL_SELLERS], PR.[TOTAL_PAYOUTS], PR.[TOTAL_AMOUNT], PR.[SUCCESSFUL_PAYOUTS], PR.[FAILED_PAYOUTS] 
FROM [PAYOUT_REPORTS] PR 
WHERE PR.[IsDeleted] = 0 
	AND PR.[PAYOUT_PERIOD_ID] = @PRM_PAYOUT_REPORT_PAYOUT_PERIOD_ID 
ORDER BY PR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 