-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [NAME],
    [IS_ACTIVE],
    [DESCRIPTION]
FROM [dbo].[COMMISSION_MODELS]
WHERE
    [ID] = @PRM_COMMISSION_MODEL_ID
    AND [IsDeleted] = 0;