// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.SellerManagementModule.Application.Dtos.SellerPerformanceReview;

namespace QuickCode.Demo.SellerManagementModule.Persistence.Repositories;
internal static class SellerPerformanceReviewCrudSqlBindings
{
    public const string StoreTableName = "SELLER_PERFORMANCE_REVIEWS";
    public const string ParameterNamePrefix = "SELLER_PERFORMANCE_REVIEW";
    public const string IdParameterName = "PRM_SELLER_PERFORMANCE_REVIEW_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByPk = "GetByPk";
        public const string GetBySellerId = "GetBySellerId";
        public const string GetSellerAverageRating = "GetSellerAverageRating";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("SELLER_ID", nameof(SellerPerformanceReviewDto.SellerId)),
        ("REVIEWER_ID", nameof(SellerPerformanceReviewDto.ReviewerId)),
        ("RATING", nameof(SellerPerformanceReviewDto.Rating)),
        ("COMMENT", nameof(SellerPerformanceReviewDto.Comment)),
        ("REVIEW_DATE", nameof(SellerPerformanceReviewDto.ReviewDate))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("SELLER_ID", nameof(SellerPerformanceReviewDto.SellerId)),
        ("REVIEWER_ID", nameof(SellerPerformanceReviewDto.ReviewerId)),
        ("RATING", nameof(SellerPerformanceReviewDto.Rating)),
        ("COMMENT", nameof(SellerPerformanceReviewDto.Comment)),
        ("REVIEW_DATE", nameof(SellerPerformanceReviewDto.ReviewDate)),
        ("ID", nameof(SellerPerformanceReviewDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(SellerPerformanceReviewDto.Id))
    };
}