-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [PRODUCT_VARIANTS] 
	SET [PRICE] = @PRODUCT_VARIANT_PRICE 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_PRODUCT_VARIANT_ID