-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT FA.[ID], FA.[SELLER_ID], FA.[AMOUNT], FA.[REASON], FA.[CREATED_DATE] 
FROM [FINANCIAL_ADJUSTMENTS] FA 
WHERE FA.[IsDeleted] = 0 
	AND FA.[PAYOUT_ID] = @PRM_FINANCIAL_ADJUSTMENT_PAYOUT_ID 
ORDER BY FA.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 