// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Models;
using QuickCode.Demo.Portal.Models.FinanceSettlementModule;
using QuickCode.Demo.Portal.Helpers;
using QuickCode.Demo.Infrastructure.Integration.Models;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using FinanceSettlementModuleContracts = QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.FinanceSettlementModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Demo.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Demo.Portal.Controllers.FinanceSettlementModule
{
    [Permission("FinanceSettlementModuleCommissionModels")]
    [Area("FinanceSettlementModule")]
    [Route("FinanceSettlementModuleCommissionModels")]
    public partial class CommissionModelsController : BaseController
    {
        private readonly FinanceSettlementModuleContracts.ICommissionModelsClient pageClient;
        public CommissionModelsController(FinanceSettlementModuleContracts.ICommissionModelsClient pageClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(CommissionModelData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("ListPartial")]
        [HttpPost]
        public async Task<IActionResult> ListPartial(CommissionModelData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return PartialView("_ListTable", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(CommissionModelData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.CommissionModelsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(CommissionModelData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.CommissionModelsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(CommissionModelData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.CommissionModelsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(CommissionModelData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(CommissionModelData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(CommissionModelData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(CommissionModelData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<CommissionModelData> PrepareModel()
        {
            var model = GetModel<CommissionModelData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<CommissionModelData> PrepareModel(CommissionModelData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            var result = await pageClient.CommissionModelsListAsync(model.CurrentPage, model.PageSize, includeCount: true);
            model.NumberOfRecord = result?.TotalCount ?? 0;
            model.TotalPage = model.PageSize <= 0 ? 0 : (model.NumberOfRecord + model.PageSize - 1) / model.PageSize;
            if (model.TotalPage > 0 && model.CurrentPage > model.TotalPage)
            {
                model.CurrentPage = model.TotalPage;
                result = await pageClient.CommissionModelsListAsync(model.CurrentPage, model.PageSize, includeCount: false);
            }

            model.List = result?.Items?.ToList() ?? new();
            return model;
        }

        [Route("Queries/GetActive")]
        public async Task<IActionResult> QueryGetActive()
        {
            var model = GetModel<CommissionModelGetActiveData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryGetActiveModel(model);
            return View("GetActive", model);
        }

        [Route("Queries/GetActive")]
        [HttpPost]
        public async Task<IActionResult> QueryGetActive(CommissionModelGetActiveData model)
        {
            model = await PrepareQueryGetActiveModel(model);
            return View("GetActive", model);
        }

        [Route("Queries/GetActivePartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetActivePartial(CommissionModelGetActiveData model)
        {
            model = await PrepareQueryGetActiveModel(model);
            return PartialView("_GetActiveTable", model);
        }

        private async Task<CommissionModelGetActiveData> PrepareQueryGetActiveModel(CommissionModelGetActiveData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.CommissionModelsGetActiveAsync(pageNumber: model.CurrentPage, pageSize: model.PageSize);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                var hasMore = model.List.Count >= model.PageSize;
                var seen = ((model.CurrentPage - 1) * model.PageSize) + model.List.Count;
                model.NumberOfRecord = seen;
                model.TotalPage = hasMore ? model.CurrentPage + 1 : model.CurrentPage;
                model.HasMoreRecords = hasMore;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/SearchByName")]
        public async Task<IActionResult> QuerySearchByName()
        {
            var model = GetModel<CommissionModelSearchByNameData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            return View("SearchByName", model);
        }

        [Route("Queries/SearchByName")]
        [HttpPost]
        public async Task<IActionResult> QuerySearchByName(CommissionModelSearchByNameData model)
        {
            model = await PrepareQuerySearchByNameModel(model);
            return View("SearchByName", model);
        }

        [Route("Queries/SearchByNamePartial")]
        [HttpPost]
        public async Task<IActionResult> QuerySearchByNamePartial(CommissionModelSearchByNameData model)
        {
            model = await PrepareQuerySearchByNameModel(model);
            return PartialView("_SearchByNameTable", model);
        }

        private async Task<CommissionModelSearchByNameData> PrepareQuerySearchByNameModel(CommissionModelSearchByNameData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            try
            {
                var result = await pageClient.CommissionModelsSearchByNameAsync(model.CommissionModelModelName, pageNumber: model.CurrentPage, pageSize: model.PageSize);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                var hasMore = model.List.Count >= model.PageSize;
                var seen = ((model.CurrentPage - 1) * model.PageSize) + model.List.Count;
                model.NumberOfRecord = seen;
                model.TotalPage = hasMore ? model.CurrentPage + 1 : model.CurrentPage;
                model.HasMoreRecords = hasMore;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }
    }
}