// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Models;
using QuickCode.Demo.Portal.Models.FinanceSettlementModule;
using QuickCode.Demo.Portal.Helpers;
using QuickCode.Demo.Infrastructure.Integration.Models;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.IdentityModuleApi.Contracts;
using FinanceSettlementModuleContracts = QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.FinanceSettlementModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Demo.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Demo.Portal.Controllers.FinanceSettlementModule
{
    [Permission("FinanceSettlementModulePayoutReports")]
    [Area("FinanceSettlementModule")]
    [Route("FinanceSettlementModulePayoutReports")]
    public partial class PayoutReportsController : BaseController
    {
        private readonly FinanceSettlementModuleContracts.IPayoutReportsClient pageClient;
        private readonly FinanceSettlementModuleContracts.IPayoutPeriodsClient pagePayoutPeriodClient;
        public PayoutReportsController(FinanceSettlementModuleContracts.IPayoutReportsClient pageClient, FinanceSettlementModuleContracts.IPayoutPeriodsClient pagePayoutPeriodClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pagePayoutPeriodClient = pagePayoutPeriodClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(PayoutReportData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("ListPartial")]
        [HttpPost]
        public async Task<IActionResult> ListPartial(PayoutReportData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return PartialView("_ListTable", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(PayoutReportData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.PayoutReportsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(PayoutReportData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.PayoutReportsUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(PayoutReportData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.PayoutReportsDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(PayoutReportData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(PayoutReportData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(PayoutReportData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(PayoutReportData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<PayoutReportData> PrepareModel()
        {
            var model = GetModel<PayoutReportData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<PayoutReportData> PrepareModel(PayoutReportData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            var result = await pageClient.PayoutReportsListAsync(model.CurrentPage, model.PageSize, includeCount: true);
            model.NumberOfRecord = result?.TotalCount ?? 0;
            model.TotalPage = model.PageSize <= 0 ? 0 : (model.NumberOfRecord + model.PageSize - 1) / model.PageSize;
            if (model.TotalPage > 0 && model.CurrentPage > model.TotalPage)
            {
                model.CurrentPage = model.TotalPage;
                result = await pageClient.PayoutReportsListAsync(model.CurrentPage, model.PageSize, includeCount: false);
            }

            model.List = result?.Items?.ToList() ?? new();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("PayoutPeriods", async () => ToComboItems((await pagePayoutPeriodClient.PayoutPeriodsListAsync())?.Items)));
            return comboBoxList;
        }

        [Route("Queries/GetByPeriod")]
        public async Task<IActionResult> QueryGetByPeriod()
        {
            var model = GetModel<PayoutReportGetByPeriodData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model.HasRun = false;
            model.List = new();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            return View("GetByPeriod", model);
        }

        [Route("Queries/GetByPeriod")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByPeriod(PayoutReportGetByPeriodData model)
        {
            model = await PrepareQueryGetByPeriodModel(model);
            return View("GetByPeriod", model);
        }

        [Route("Queries/GetByPeriodPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetByPeriodPartial(PayoutReportGetByPeriodData model)
        {
            model = await PrepareQueryGetByPeriodModel(model);
            return PartialView("_GetByPeriodTable", model);
        }

        private async Task<PayoutReportGetByPeriodData> PrepareQueryGetByPeriodModel(PayoutReportGetByPeriodData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.PayoutReportsGetByPeriodAsync(model.PayoutReportPayoutPeriodId, pageNumber: model.CurrentPage, pageSize: model.PageSize);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                var hasMore = model.List.Count >= model.PageSize;
                var seen = ((model.CurrentPage - 1) * model.PageSize) + model.List.Count;
                model.NumberOfRecord = seen;
                model.TotalPage = hasMore ? model.CurrentPage + 1 : model.CurrentPage;
                model.HasMoreRecords = hasMore;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetLatestReport")]
        public async Task<IActionResult> QueryGetLatestReport()
        {
            var model = GetModel<PayoutReportGetLatestReportData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryGetLatestReportModel(model);
            return View("GetLatestReport", model);
        }

        [Route("Queries/GetLatestReport")]
        [HttpPost]
        public async Task<IActionResult> QueryGetLatestReport(PayoutReportGetLatestReportData model)
        {
            model = await PrepareQueryGetLatestReportModel(model);
            return View("GetLatestReport", model);
        }

        [Route("Queries/GetLatestReportPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetLatestReportPartial(PayoutReportGetLatestReportData model)
        {
            model = await PrepareQueryGetLatestReportModel(model);
            return PartialView("_GetLatestReportTable", model);
        }

        private async Task<PayoutReportGetLatestReportData> PrepareQueryGetLatestReportModel(PayoutReportGetLatestReportData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.PayoutReportsGetLatestReportAsync();
                model.List = result == null ? new() : new List<dynamic>
                {
                    result
                };
                model.NumberOfRecord = model.List.Count;
                model.TotalPage = 1;
                model.CurrentPage = 1;
                model.HasMoreRecords = false;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }

        [Route("Queries/GetRecentReports")]
        public async Task<IActionResult> QueryGetRecentReports()
        {
            var model = GetModel<PayoutReportGetRecentReportsData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            model = await PrepareQueryGetRecentReportsModel(model);
            return View("GetRecentReports", model);
        }

        [Route("Queries/GetRecentReports")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentReports(PayoutReportGetRecentReportsData model)
        {
            model = await PrepareQueryGetRecentReportsModel(model);
            return View("GetRecentReports", model);
        }

        [Route("Queries/GetRecentReportsPartial")]
        [HttpPost]
        public async Task<IActionResult> QueryGetRecentReportsPartial(PayoutReportGetRecentReportsData model)
        {
            model = await PrepareQueryGetRecentReportsModel(model);
            return PartialView("_GetRecentReportsTable", model);
        }

        private async Task<PayoutReportGetRecentReportsData> PrepareQueryGetRecentReportsModel(PayoutReportGetRecentReportsData model)
        {
            model.PageSize = ResolvePageSize(model.PageSize);
            if (model.CurrentPage < 1)
                model.CurrentPage = 1;
            model.HasRun = true;
            model.ErrorMessage = null;
            model.QueryHttpStatus = null;
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            try
            {
                var result = await pageClient.PayoutReportsGetRecentReportsAsync(pageNumber: model.CurrentPage, pageSize: model.PageSize);
                model.List = result?.Cast<dynamic>().ToList() ?? new();
                var hasMore = model.List.Count >= model.PageSize;
                var seen = ((model.CurrentPage - 1) * model.PageSize) + model.List.Count;
                model.NumberOfRecord = seen;
                model.TotalPage = hasMore ? model.CurrentPage + 1 : model.CurrentPage;
                model.HasMoreRecords = hasMore;
            }
            catch (QuickCodeSwaggerException ex)
            {
                model.List = new();
                model.NumberOfRecord = 0;
                model.TotalPage = 1;
                model.HasMoreRecords = false;
                model.QueryHttpStatus = ex.StatusCode;
                model.ErrorMessage = FormatPortalQueryError(ex);
            }

            return model;
        }
    }
}