// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CampaignApplicability;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CampaignApplicability
{
    public class GetItemCampaignApplicabilityQuery : IRequest<Response<CampaignApplicabilityDto>>
    {
        public int CampaignId { get; set; }
        public RuleScope Scope { get; set; }
        public int ScopeId { get; set; }

        public GetItemCampaignApplicabilityQuery(int campaignId, RuleScope scope, int scopeId)
        {
            this.CampaignId = campaignId;
            this.Scope = scope;
            this.ScopeId = scopeId;
        }

        public class GetItemCampaignApplicabilityHandler : IRequestHandler<GetItemCampaignApplicabilityQuery, Response<CampaignApplicabilityDto>>
        {
            private readonly ILogger<GetItemCampaignApplicabilityHandler> _logger;
            private readonly ICampaignApplicabilityRepository _repository;
            public GetItemCampaignApplicabilityHandler(ILogger<GetItemCampaignApplicabilityHandler> logger, ICampaignApplicabilityRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<CampaignApplicabilityDto>> Handle(GetItemCampaignApplicabilityQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.CampaignId, request.Scope, request.ScopeId);
                return returnValue.ToResponse();
            }
        }
    }
}