-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [SELLER_COMMISSION_ASSIGNMENTS] 
WHERE [SELLER_ID] = @PRM_SELLER_COMMISSION_ASSIGNMENT_SELLER_ID