IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_DOCUMENTS', N'U') AND name = N'IX_SELLER_DOCUMENTS_SELLER_ID')
BEGIN
    CREATE INDEX [IX_SELLER_DOCUMENTS_SELLER_ID] ON [dbo].[SELLER_DOCUMENTS] ([SELLER_ID]);
END