IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_PERFORMANCE_REVIEWS', N'U') AND name = N'IX_SELLER_PERFORMANCE_REVIEWS_IsDeleted')
BEGIN
    CREATE INDEX [IX_SELLER_PERFORMANCE_REVIEWS_IsDeleted] ON [dbo].[SELLER_PERFORMANCE_REVIEWS] ([IsDeleted]);
END