IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLERS_SELLER_TIERS_SELLER_TIER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLERS'))
BEGIN
    ALTER TABLE [dbo].[SELLERS] ADD CONSTRAINT [FK_SELLERS_SELLER_TIERS_SELLER_TIER_ID] FOREIGN KEY ([SELLER_TIER_ID]) REFERENCES [dbo].[SELLER_TIERS] ([ID]);
END