IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.STORES', N'U') AND name = N'IX_STORES_SELLER_ID')
BEGIN
    CREATE INDEX [IX_STORES_SELLER_ID] ON [dbo].[STORES] ([SELLER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.STORES', N'U') AND name = N'IX_STORES_SLUG')
BEGIN
    CREATE INDEX [IX_STORES_SLUG] ON [dbo].[STORES] ([SLUG]);
END