IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLERS', N'U') AND name = N'IX_SELLERS_SELLER_TIER_ID')
BEGIN
    CREATE INDEX [IX_SELLERS_SELLER_TIER_ID] ON [dbo].[SELLERS] ([SELLER_TIER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLERS', N'U') AND name = N'IX_SELLERS_STATUS')
BEGIN
    CREATE INDEX [IX_SELLERS_STATUS] ON [dbo].[SELLERS] ([STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLERS', N'U') AND name = N'IX_SELLERS_USER_ID')
BEGIN
    CREATE INDEX [IX_SELLERS_USER_ID] ON [dbo].[SELLERS] ([USER_ID]);
END