IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLERS_SELLER_TIERS_SELLER_TIER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLERS'))
BEGIN
    ALTER TABLE [dbo].[SELLERS] ADD CONSTRAINT [FK_SELLERS_SELLER_TIERS_SELLER_TIER_ID] FOREIGN KEY ([SELLER_TIER_ID]) REFERENCES [dbo].[SELLER_TIERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_BANK_ACCOUNTS_SELLERS_SELLER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_BANK_ACCOUNTS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_BANK_ACCOUNTS] ADD CONSTRAINT [FK_SELLER_BANK_ACCOUNTS_SELLERS_SELLER_ID] FOREIGN KEY ([SELLER_ID]) REFERENCES [dbo].[SELLERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_DOCUMENTS_SELLERS_SELLER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_DOCUMENTS] ADD CONSTRAINT [FK_SELLER_DOCUMENTS_SELLERS_SELLER_ID] FOREIGN KEY ([SELLER_ID]) REFERENCES [dbo].[SELLERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_PERFORMANCE_REVIEWS_SELLERS_SELLER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_PERFORMANCE_REVIEWS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_PERFORMANCE_REVIEWS] ADD CONSTRAINT [FK_SELLER_PERFORMANCE_REVIEWS_SELLERS_SELLER_ID] FOREIGN KEY ([SELLER_ID]) REFERENCES [dbo].[SELLERS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_STORES_SELLERS_SELLER_ID' AND parent_object_id = OBJECT_ID(N'dbo.STORES'))
BEGIN
    ALTER TABLE [dbo].[STORES] ADD CONSTRAINT [FK_STORES_SELLERS_SELLER_ID] FOREIGN KEY ([SELLER_ID]) REFERENCES [dbo].[SELLERS] ([ID]);
END