IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_SELLER_DOCUMENTS_SELLERS_SELLER_ID' AND parent_object_id = OBJECT_ID(N'dbo.SELLER_DOCUMENTS'))
BEGIN
    ALTER TABLE [dbo].[SELLER_DOCUMENTS] ADD CONSTRAINT [FK_SELLER_DOCUMENTS_SELLERS_SELLER_ID] FOREIGN KEY ([SELLER_ID]) REFERENCES [dbo].[SELLERS] ([ID]);
END