IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_BANK_ACCOUNTS', N'U') AND name = N'IX_SELLER_BANK_ACCOUNTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_SELLER_BANK_ACCOUNTS_IsDeleted] ON [dbo].[SELLER_BANK_ACCOUNTS] ([IsDeleted]);
END