IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_STORES_SELLERS_SELLER_ID' AND parent_object_id = OBJECT_ID(N'dbo.STORES'))
BEGIN
    ALTER TABLE [dbo].[STORES] ADD CONSTRAINT [FK_STORES_SELLERS_SELLER_ID] FOREIGN KEY ([SELLER_ID]) REFERENCES [dbo].[SELLERS] ([ID]);
END