IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_BANK_ACCOUNTS', N'U') AND name = N'IX_SELLER_BANK_ACCOUNTS_SELLER_ID_IS_DEFAULT')
BEGIN
    CREATE INDEX [IX_SELLER_BANK_ACCOUNTS_SELLER_ID_IS_DEFAULT] ON [dbo].[SELLER_BANK_ACCOUNTS] ([SELLER_ID], [IS_DEFAULT]);
END