-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
DELETE FROM [CAMPAIGN_APPLICABILITIES] 
WHERE [CAMPAIGN_ID] = @PRM_CAMPAIGN_APPLICABILITY_CAMPAIGN_ID 
	AND [SCOPE] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE 
	AND [SCOPE_ID] = @PRM_CAMPAIGN_APPLICABILITY_SCOPE_ID