-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
INSERT INTO [dbo].[COMMISSION_MODELS] (
    [MODEL_NAME],
    [DESCRIPTION],
    [COMMISSION_PERCENTAGE],
    [IS_ACTIVE],
    [CREATED_DATE]
)
OUTPUT INSERTED.*
VALUES (
    @PRM_COMMISSION_MODEL_MODEL_NAME,
    @PRM_COMMISSION_MODEL_DESCRIPTION,
    @PRM_COMMISSION_MODEL_COMMISSION_PERCENTAGE,
    @PRM_COMMISSION_MODEL_IS_ACTIVE,
    @PRM_COMMISSION_MODEL_CREATED_DATE
    );