-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[COMMISSION_MODELS]
SET
    [MODEL_NAME] = @PRM_COMMISSION_MODEL_MODEL_NAME,
    [DESCRIPTION] = @PRM_COMMISSION_MODEL_DESCRIPTION,
    [COMMISSION_PERCENTAGE] = @PRM_COMMISSION_MODEL_COMMISSION_PERCENTAGE,
    [IS_ACTIVE] = @PRM_COMMISSION_MODEL_IS_ACTIVE,
    [CREATED_DATE] = @PRM_COMMISSION_MODEL_CREATED_DATE
WHERE
    [ID] = @PRM_COMMISSION_MODEL_ID
    AND [IsDeleted] = 0;