-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[ORDER_STATUS_HISTORIES]
SET
    [ORDER_ID] = @PRM_ORDER_STATUS_HISTORY_ORDER_ID,
    [PREVIOUS_STATUS] = @PRM_ORDER_STATUS_HISTORY_PREVIOUS_STATUS,
    [NEW_STATUS] = @PRM_ORDER_STATUS_HISTORY_NEW_STATUS,
    [CHANGED_BY_USER_ID] = @PRM_ORDER_STATUS_HISTORY_CHANGED_BY_USER_ID,
    [CHANGE_DATE] = @PRM_ORDER_STATUS_HISTORY_CHANGE_DATE,
    [NOTES] = @PRM_ORDER_STATUS_HISTORY_NOTES
WHERE
    [ID] = @PRM_ORDER_STATUS_HISTORY_ID
    AND [IsDeleted] = 0;