// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.AttributeValue;

namespace QuickCode.Demo.ProductCatalogModule.Persistence.Repositories;
internal static class AttributeValueCrudSqlBindings
{
    public const string StoreTableName = "ATTRIBUTE_VALUES";
    public const string ParameterNamePrefix = "ATTRIBUTE_VALUE";
    public const string IdParameterName = "PRM_ATTRIBUTE_VALUE_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByAttributeId = "GetByAttributeId";
        public const string GetByPk = "GetByPk";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("ATTRIBUTE_ID", nameof(AttributeValueDto.AttributeId)),
        ("VALUE", nameof(AttributeValueDto.Value))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("ATTRIBUTE_ID", nameof(AttributeValueDto.AttributeId)),
        ("VALUE", nameof(AttributeValueDto.Value)),
        ("ID", nameof(AttributeValueDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(AttributeValueDto.Id))
    };
}