// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionRule;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.CommissionRule
{
    public class GetActiveRulesQuery : IRequest<Response<List<GetActiveRulesResponseDto>>>
    {
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetActiveRulesQuery(int? pageNumber, int? pageSize)
        {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetActiveRulesHandler : IRequestHandler<GetActiveRulesQuery, Response<List<GetActiveRulesResponseDto>>>
        {
            private readonly ILogger<GetActiveRulesHandler> _logger;
            private readonly ICommissionRuleRepository _repository;
            public GetActiveRulesHandler(ILogger<GetActiveRulesHandler> logger, ICommissionRuleRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetActiveRulesResponseDto>>> Handle(GetActiveRulesQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetActiveRulesAsync(request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}