IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ATTRIBUTE_VALUES_ATTRIBUTE_DEFINITIONS_ATTRIBUTE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ATTRIBUTE_VALUES'))
BEGIN
    ALTER TABLE [dbo].[ATTRIBUTE_VALUES] ADD CONSTRAINT [FK_ATTRIBUTE_VALUES_ATTRIBUTE_DEFINITIONS_ATTRIBUTE_ID] FOREIGN KEY ([ATTRIBUTE_ID]) REFERENCES [dbo].[ATTRIBUTE_DEFINITIONS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORIES_CATEGORIES_PARENT_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORIES] ADD CONSTRAINT [FK_CATEGORIES_CATEGORIES_PARENT_CATEGORY_ID] FOREIGN KEY ([PARENT_CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCTS_BRANDS_BRAND_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCTS'))
BEGIN
    ALTER TABLE [dbo].[PRODUCTS] ADD CONSTRAINT [FK_PRODUCTS_BRANDS_BRAND_ID] FOREIGN KEY ([BRAND_ID]) REFERENCES [dbo].[BRANDS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCTS_CATEGORIES_PRIMARY_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCTS'))
BEGIN
    ALTER TABLE [dbo].[PRODUCTS] ADD CONSTRAINT [FK_PRODUCTS_CATEGORIES_PRIMARY_CATEGORY_ID] FOREIGN KEY ([PRIMARY_CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_CATEGORIES_PRODUCTS_PRODUCT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_CATEGORIES] ADD CONSTRAINT [FK_PRODUCT_CATEGORIES_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[PRODUCTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_CATEGORIES_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_CATEGORIES] ADD CONSTRAINT [FK_PRODUCT_CATEGORIES_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_VARIANTS_PRODUCTS_PRODUCT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANTS'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_VARIANTS] ADD CONSTRAINT [FK_PRODUCT_VARIANTS_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[PRODUCTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_VARIANT_ATTRIBUTES_PRODUCT_VARIANTS_VARIANT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANT_ATTRIBUTES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_VARIANT_ATTRIBUTES] ADD CONSTRAINT [FK_PRODUCT_VARIANT_ATTRIBUTES_PRODUCT_VARIANTS_VARIANT_ID] FOREIGN KEY ([VARIANT_ID]) REFERENCES [dbo].[PRODUCT_VARIANTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_VARIANT_ATTRIBUTES_ATTRIBUTE_VALUES_ATTRIBUTE_VALUE_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANT_ATTRIBUTES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_VARIANT_ATTRIBUTES] ADD CONSTRAINT [FK_PRODUCT_VARIANT_ATTRIBUTES_ATTRIBUTE_VALUES_ATTRIBUTE_VALUE_ID] FOREIGN KEY ([ATTRIBUTE_VALUE_ID]) REFERENCES [dbo].[ATTRIBUTE_VALUES] ([ID]);
END