IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_CATEGORIES_PRODUCTS_PRODUCT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_CATEGORIES] ADD CONSTRAINT [FK_PRODUCT_CATEGORIES_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[PRODUCTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_CATEGORIES_CATEGORIES_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_CATEGORIES] ADD CONSTRAINT [FK_PRODUCT_CATEGORIES_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END