IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANTS', N'U') AND name = N'IX_PRODUCT_VARIANTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_PRODUCT_VARIANTS_IsDeleted] ON [dbo].[PRODUCT_VARIANTS] ([IsDeleted]);
END