IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ATTRIBUTE_VALUES', N'U') AND name = N'IX_ATTRIBUTE_VALUES_IsDeleted')
BEGIN
    CREATE INDEX [IX_ATTRIBUTE_VALUES_IsDeleted] ON [dbo].[ATTRIBUTE_VALUES] ([IsDeleted]);
END