IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORIES', N'U') AND name = N'IX_CATEGORIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_CATEGORIES_IsDeleted] ON [dbo].[CATEGORIES] ([IsDeleted]);
END