IF OBJECT_ID(N'dbo.PRODUCT_VARIANT_ATTRIBUTES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PRODUCT_VARIANT_ATTRIBUTES] (
        [VARIANT_ID] int NOT NULL,
        [ATTRIBUTE_VALUE_ID] int NOT NULL,
        CONSTRAINT [PK_PRODUCT_VARIANT_ATTRIBUTES] PRIMARY KEY ([VARIANT_ID], [ATTRIBUTE_VALUE_ID])
    );
END;