IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ATTRIBUTE_DEFINITIONS', N'U') AND name = N'IX_ATTRIBUTE_DEFINITIONS_CODE')
BEGIN
    CREATE INDEX [IX_ATTRIBUTE_DEFINITIONS_CODE] ON [dbo].[ATTRIBUTE_DEFINITIONS] ([CODE]);
END