IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANTS', N'U') AND name = N'IX_PRODUCT_VARIANTS_PRODUCT_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_PRODUCT_VARIANTS_PRODUCT_ID_IS_ACTIVE] ON [dbo].[PRODUCT_VARIANTS] ([PRODUCT_ID], [IS_ACTIVE]);
END