IF OBJECT_ID(N'dbo.PRODUCT_CATEGORIES', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[PRODUCT_CATEGORIES] (
        [PRODUCT_ID] int NOT NULL,
        [CATEGORY_ID] int NOT NULL,
        CONSTRAINT [PK_PRODUCT_CATEGORIES] PRIMARY KEY ([PRODUCT_ID], [CATEGORY_ID])
    );
END;