IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCTS', N'U') AND name = N'IX_PRODUCTS_BRAND_ID')
BEGIN
    CREATE INDEX [IX_PRODUCTS_BRAND_ID] ON [dbo].[PRODUCTS] ([BRAND_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCTS', N'U') AND name = N'IX_PRODUCTS_PRIMARY_CATEGORY_ID_BRAND_ID')
BEGIN
    CREATE INDEX [IX_PRODUCTS_PRIMARY_CATEGORY_ID_BRAND_ID] ON [dbo].[PRODUCTS] ([PRIMARY_CATEGORY_ID], [BRAND_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCTS', N'U') AND name = N'IX_PRODUCTS_SELLER_ID_STATUS')
BEGIN
    CREATE INDEX [IX_PRODUCTS_SELLER_ID_STATUS] ON [dbo].[PRODUCTS] ([SELLER_ID], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCTS', N'U') AND name = N'IX_PRODUCTS_SKU')
BEGIN
    CREATE INDEX [IX_PRODUCTS_SKU] ON [dbo].[PRODUCTS] ([SKU]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PRODUCTS', N'U') AND name = N'IX_PRODUCTS_STATUS')
BEGIN
    CREATE INDEX [IX_PRODUCTS_STATUS] ON [dbo].[PRODUCTS] ([STATUS]);
END