IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCTS_BRANDS_BRAND_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCTS'))
BEGIN
    ALTER TABLE [dbo].[PRODUCTS] ADD CONSTRAINT [FK_PRODUCTS_BRANDS_BRAND_ID] FOREIGN KEY ([BRAND_ID]) REFERENCES [dbo].[BRANDS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCTS_CATEGORIES_PRIMARY_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCTS'))
BEGIN
    ALTER TABLE [dbo].[PRODUCTS] ADD CONSTRAINT [FK_PRODUCTS_CATEGORIES_PRIMARY_CATEGORY_ID] FOREIGN KEY ([PRIMARY_CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END