IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_VARIANTS_PRODUCTS_PRODUCT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANTS'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_VARIANTS] ADD CONSTRAINT [FK_PRODUCT_VARIANTS_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[PRODUCTS] ([ID]);
END