IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORIES', N'U') AND name = N'IX_CATEGORIES_PARENT_CATEGORY_ID_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_CATEGORIES_PARENT_CATEGORY_ID_IS_ACTIVE] ON [dbo].[CATEGORIES] ([PARENT_CATEGORY_ID], [IS_ACTIVE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.CATEGORIES', N'U') AND name = N'IX_CATEGORIES_SLUG_IS_ACTIVE')
BEGIN
    CREATE INDEX [IX_CATEGORIES_SLUG_IS_ACTIVE] ON [dbo].[CATEGORIES] ([SLUG], [IS_ACTIVE]);
END