IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_VARIANT_ATTRIBUTES_PRODUCT_VARIANTS_VARIANT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANT_ATTRIBUTES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_VARIANT_ATTRIBUTES] ADD CONSTRAINT [FK_PRODUCT_VARIANT_ATTRIBUTES_PRODUCT_VARIANTS_VARIANT_ID] FOREIGN KEY ([VARIANT_ID]) REFERENCES [dbo].[PRODUCT_VARIANTS] ([ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PRODUCT_VARIANT_ATTRIBUTES_ATTRIBUTE_VALUES_ATTRIBUTE_VALUE_ID' AND parent_object_id = OBJECT_ID(N'dbo.PRODUCT_VARIANT_ATTRIBUTES'))
BEGIN
    ALTER TABLE [dbo].[PRODUCT_VARIANT_ATTRIBUTES] ADD CONSTRAINT [FK_PRODUCT_VARIANT_ATTRIBUTES_ATTRIBUTE_VALUES_ATTRIBUTE_VALUE_ID] FOREIGN KEY ([ATTRIBUTE_VALUE_ID]) REFERENCES [dbo].[ATTRIBUTE_VALUES] ([ID]);
END