IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ATTRIBUTE_VALUES_ATTRIBUTE_DEFINITIONS_ATTRIBUTE_ID' AND parent_object_id = OBJECT_ID(N'dbo.ATTRIBUTE_VALUES'))
BEGIN
    ALTER TABLE [dbo].[ATTRIBUTE_VALUES] ADD CONSTRAINT [FK_ATTRIBUTE_VALUES_ATTRIBUTE_DEFINITIONS_ATTRIBUTE_ID] FOREIGN KEY ([ATTRIBUTE_ID]) REFERENCES [dbo].[ATTRIBUTE_DEFINITIONS] ([ID]);
END