IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_CATEGORIES_CATEGORIES_PARENT_CATEGORY_ID' AND parent_object_id = OBJECT_ID(N'dbo.CATEGORIES'))
BEGIN
    ALTER TABLE [dbo].[CATEGORIES] ADD CONSTRAINT [FK_CATEGORIES_CATEGORIES_PARENT_CATEGORY_ID] FOREIGN KEY ([PARENT_CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([ID]);
END