IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ATTRIBUTE_VALUES', N'U') AND name = N'IX_ATTRIBUTE_VALUES_ATTRIBUTE_ID')
BEGIN
    CREATE INDEX [IX_ATTRIBUTE_VALUES_ATTRIBUTE_ID] ON [dbo].[ATTRIBUTE_VALUES] ([ATTRIBUTE_ID]);
END