// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionEntry;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.CommissionEntry
{
    public class GetItemCommissionEntryQuery : IRequest<Response<CommissionEntryDto>>
    {
        public int Id { get; set; }

        public GetItemCommissionEntryQuery(int id)
        {
            this.Id = id;
        }

        public class GetItemCommissionEntryHandler : IRequestHandler<GetItemCommissionEntryQuery, Response<CommissionEntryDto>>
        {
            private readonly ILogger<GetItemCommissionEntryHandler> _logger;
            private readonly ICommissionEntryRepository _repository;
            public GetItemCommissionEntryHandler(ILogger<GetItemCommissionEntryHandler> logger, ICommissionEntryRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<CommissionEntryDto>> Handle(GetItemCommissionEntryQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPkAsync(request.Id);
                return returnValue.ToResponse();
            }
        }
    }
}