-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT OSH.[ID], OSH.[NEW_STATUS], OSH.[CHANGE_DATE], OSH.[NOTES] 
FROM [ORDER_STATUS_HISTORIES] OSH 
WHERE OSH.[IsDeleted] = 0 
	AND OSH.[ORDER_ID] = @PRM_ORDER_STATUS_HISTORY_ORDER_ID 
ORDER BY OSH.[CHANGE_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 