-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT
    [ID],
    [ORDER_ID],
    [PRODUCT_VARIANT_ID],
    [PRODUCT_NAME],
    [SKU],
    [QUANTITY],
    [UNIT_PRICE],
    [TOTAL_PRICE]
FROM [dbo].[ORDER_ITEMS]
WHERE
    [ID] = @PRM_ORDER_ITEM_ID
    AND [IsDeleted] = 0;