// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.ReturnRequest;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Features.ReturnRequest
{
    public class DeleteReturnRequestCommand : IRequest<Response<bool>>
    {
        public ReturnRequestDto request { get; set; }

        public DeleteReturnRequestCommand(ReturnRequestDto request)
        {
            this.request = request;
        }

        public class DeleteReturnRequestHandler : IRequestHandler<DeleteReturnRequestCommand, Response<bool>>
        {
            private readonly ILogger<DeleteReturnRequestHandler> _logger;
            private readonly IReturnRequestRepository _repository;
            public DeleteReturnRequestHandler(ILogger<DeleteReturnRequestHandler> logger, IReturnRequestRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(DeleteReturnRequestCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.DeleteAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}