// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionModel;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CommissionModel
{
    public class DeleteItemCommissionModelCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }

        public DeleteItemCommissionModelCommand(int id)
        {
            this.Id = id;
        }

        public class DeleteItemCommissionModelHandler : IRequestHandler<DeleteItemCommissionModelCommand, Response<bool>>
        {
            private readonly ILogger<DeleteItemCommissionModelHandler> _logger;
            private readonly ICommissionModelRepository _repository;
            public DeleteItemCommissionModelHandler(ILogger<DeleteItemCommissionModelHandler> logger, ICommissionModelRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(DeleteItemCommissionModelCommand request, CancellationToken cancellationToken)
            {
                var deleteItem = await _repository.GetByPkAsync(request.Id);
                if (deleteItem.Code == 404)
                    return Response<bool>.NotFound();
                var returnValue = await _repository.DeleteAsync(deleteItem.Value);
                return returnValue.ToResponse();
            }
        }
    }
}