// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.Shipment;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Features.Shipment
{
    public class MarkAsDeliveredCommand : IRequest<Response<int>>
    {
        public int ShipmentId { get; set; }
        public MarkAsDeliveredRequestDto UpdateRequest { get; set; }

        public MarkAsDeliveredCommand(int shipmentId, MarkAsDeliveredRequestDto updateRequest)
        {
            this.ShipmentId = shipmentId;
            this.UpdateRequest = updateRequest;
        }

        public class MarkAsDeliveredHandler : IRequestHandler<MarkAsDeliveredCommand, Response<int>>
        {
            private readonly ILogger<MarkAsDeliveredHandler> _logger;
            private readonly IShipmentRepository _repository;
            public MarkAsDeliveredHandler(ILogger<MarkAsDeliveredHandler> logger, IShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(MarkAsDeliveredCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.MarkAsDeliveredAsync(request.ShipmentId, request.UpdateRequest);
                return returnValue.ToResponse();
            }
        }
    }
}