// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.Shipment;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Features.Shipment
{
    public class UpdateShipmentCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }
        public ShipmentDto request { get; set; }

        public UpdateShipmentCommand(int id, ShipmentDto request)
        {
            this.request = request;
            this.Id = id;
        }

        public class UpdateShipmentHandler : IRequestHandler<UpdateShipmentCommand, Response<bool>>
        {
            private readonly ILogger<UpdateShipmentHandler> _logger;
            private readonly IShipmentRepository _repository;
            public UpdateShipmentHandler(ILogger<UpdateShipmentHandler> logger, IShipmentRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdateShipmentCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.Id);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}