// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Category;

namespace QuickCode.Demo.ProductCatalogModule.Persistence.Repositories;
internal static class CategoryCrudSqlBindings
{
    public const string StoreTableName = "CATEGORIES";
    public const string ParameterNamePrefix = "CATEGORY";
    public const string IdParameterName = "PRM_CATEGORY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Deactivate = "Deactivate";
        public const string Delete = "Delete";
        public const string GetActive = "GetActive";
        public const string GetByPk = "GetByPk";
        public const string GetBySlug = "GetBySlug";
        public const string GetSubCategories = "GetSubCategories";
        public const string Insert = "Insert";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("PARENT_CATEGORY_ID", nameof(CategoryDto.ParentCategoryId)),
        ("NAME", nameof(CategoryDto.Name)),
        ("SLUG", nameof(CategoryDto.Slug)),
        ("ICON", nameof(CategoryDto.Icon)),
        ("BANNER", nameof(CategoryDto.Banner)),
        ("INTRO_VIDEO", nameof(CategoryDto.IntroVideo)),
        ("IS_ACTIVE", nameof(CategoryDto.IsActive))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Update = new[]
    {
        ("PARENT_CATEGORY_ID", nameof(CategoryDto.ParentCategoryId)),
        ("NAME", nameof(CategoryDto.Name)),
        ("SLUG", nameof(CategoryDto.Slug)),
        ("ICON", nameof(CategoryDto.Icon)),
        ("BANNER", nameof(CategoryDto.Banner)),
        ("INTRO_VIDEO", nameof(CategoryDto.IntroVideo)),
        ("IS_ACTIVE", nameof(CategoryDto.IsActive)),
        ("ID", nameof(CategoryDto.Id))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("ID", nameof(CategoryDto.Id))
    };
}