-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[CATEGORY_COMMISSION_OVERRIDES]
SET
    [CATEGORY_ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_CATEGORY_ID,
    [COMMISSION_MODEL_ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_COMMISSION_MODEL_ID,
    [EFFECTIVE_DATE] = @PRM_CATEGORY_COMMISSION_OVERRIDE_EFFECTIVE_DATE
WHERE
    [ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_ID
    AND [IsDeleted] = 0;