// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.PromotionalCampaign;
using System.Threading.Tasks;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories
{
    public partial interface IPromotionalCampaignRepository : IBaseRepository<PromotionalCampaignDto>
    {
        Task<RepoResponse<PromotionalCampaignDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveCampaignsResponseDto>>> GetActiveCampaignsAsync(int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetCampaignsInDateRangeResponseDto>>> GetCampaignsInDateRangeAsync(DateTime promotionalCampaignStartDateFrom, DateTime promotionalCampaignStartDateTo, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> DeactivateAsync(int promotionalCampaignId, DeactivateRequestDto updateRequest);
    }
}