// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.OrderManagementModule.Domain.Entities;
using QuickCode.Demo.OrderManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.ReturnRequest;
using QuickCode.Demo.OrderManagementModule.Application.Mappings;
using QuickCode.Demo.OrderManagementModule.Persistence.Sql;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Persistence.Repositories
{
    public partial class ReturnRequestRepository : BaseRepository, IReturnRequestRepository
    {
        public async Task<RepoResponse<int>> ApproveAsync(int returnRequestId, ApproveRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ReturnRequestCrudSqlBindings.OperationNames.Approve, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ReturnRequest.Command.Approve);
                var parameters = new
                {
                    PRM_RETURN_REQUEST_ID = returnRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> RejectAsync(int returnRequestId, RejectRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ReturnRequestCrudSqlBindings.OperationNames.Reject, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ReturnRequest.Command.Reject);
                var parameters = new
                {
                    PRM_RETURN_REQUEST_ID = returnRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> CompleteAsync(int returnRequestId, CompleteRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ReturnRequestCrudSqlBindings.OperationNames.Complete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ReturnRequest.Command.Complete);
                var parameters = new
                {
                    PRM_RETURN_REQUEST_ID = returnRequestId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}