// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.ProductCategory;

namespace QuickCode.Demo.ProductCatalogModule.Persistence.Repositories;
internal static class ProductCategoryCrudSqlBindings
{
    public const string StoreTableName = "PRODUCT_CATEGORIES";
    public const string ParameterNamePrefix = "PRODUCT_CATEGORY";
    public const string ProductIdParameterName = "PRM_PRODUCT_CATEGORY_PRODUCT_ID";
    public const string CategoryIdParameterName = "PRM_PRODUCT_CATEGORY_CATEGORY_ID";
    public static class OperationNames
    {
        public const string Count = "Count";
        public const string Delete = "Delete";
        public const string GetByCategoryId = "GetByCategoryId";
        public const string GetByPk = "GetByPk";
        public const string GetByProductId = "GetByProductId";
        public const string Insert = "Insert";
        public const string RemoveFromCategory = "RemoveFromCategory";
        public const string Select = "Select";
        public const string Update = "Update";
    }

    public static readonly (string SqlColumnName, string DtoPropertyName)[] Insert = new[]
    {
        ("PRODUCT_ID", nameof(ProductCategoryDto.ProductId)),
        ("CATEGORY_ID", nameof(ProductCategoryDto.CategoryId))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] JunctionPk = new[]
    {
        ("PRODUCT_ID", nameof(ProductCategoryDto.ProductId)),
        ("CATEGORY_ID", nameof(ProductCategoryDto.CategoryId))
    };
    public static readonly (string SqlColumnName, string DtoPropertyName)[] Delete = new[]
    {
        ("PRODUCT_ID", nameof(ProductCategoryDto.ProductId)),
        ("CATEGORY_ID", nameof(ProductCategoryDto.CategoryId))
    };
}