// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionRule
{
    public record CommissionRuleDto
    {
        public int Id { get; init; }
        public int CommissionModelId { get; init; }
        public string RuleName { get; init; }
        public decimal MinOrderValue { get; init; }
        public decimal MaxOrderValue { get; init; }
        public decimal OverridePercentage { get; init; }
        public bool IsActive { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}