-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [SELLERS] 
	SET [SELLER_TIER_ID] = @SELLER_SELLER_TIER_ID 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_SELLER_ID