IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_RULES', N'U') AND name = N'IX_COMMISSION_RULES_COMMISSION_MODEL_ID')
BEGIN
    CREATE INDEX [IX_COMMISSION_RULES_COMMISSION_MODEL_ID] ON [dbo].[COMMISSION_RULES] ([COMMISSION_MODEL_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_RULES', N'U') AND name = N'IX_COMMISSION_RULES_MIN_ORDER_VALUE_MAX_ORDER_VALUE')
BEGIN
    CREATE INDEX [IX_COMMISSION_RULES_MIN_ORDER_VALUE_MAX_ORDER_VALUE] ON [dbo].[COMMISSION_RULES] ([MIN_ORDER_VALUE], [MAX_ORDER_VALUE]);
END