IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FINANCIAL_ADJUSTMENTS', N'U') AND name = N'IX_FINANCIAL_ADJUSTMENTS_PAYOUT_ID')
BEGIN
    CREATE INDEX [IX_FINANCIAL_ADJUSTMENTS_PAYOUT_ID] ON [dbo].[FINANCIAL_ADJUSTMENTS] ([PAYOUT_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FINANCIAL_ADJUSTMENTS', N'U') AND name = N'IX_FINANCIAL_ADJUSTMENTS_REASON')
BEGIN
    CREATE INDEX [IX_FINANCIAL_ADJUSTMENTS_REASON] ON [dbo].[FINANCIAL_ADJUSTMENTS] ([REASON]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FINANCIAL_ADJUSTMENTS', N'U') AND name = N'IX_FINANCIAL_ADJUSTMENTS_SELLER_ID')
BEGIN
    CREATE INDEX [IX_FINANCIAL_ADJUSTMENTS_SELLER_ID] ON [dbo].[FINANCIAL_ADJUSTMENTS] ([SELLER_ID]);
END