IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYOUT_LINE_ITEMS', N'U') AND name = N'IX_PAYOUT_LINE_ITEMS_ORDER_ID')
BEGIN
    CREATE INDEX [IX_PAYOUT_LINE_ITEMS_ORDER_ID] ON [dbo].[PAYOUT_LINE_ITEMS] ([ORDER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYOUT_LINE_ITEMS', N'U') AND name = N'IX_PAYOUT_LINE_ITEMS_PAYOUT_ID')
BEGIN
    CREATE INDEX [IX_PAYOUT_LINE_ITEMS_PAYOUT_ID] ON [dbo].[PAYOUT_LINE_ITEMS] ([PAYOUT_ID]);
END