IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TRANSACTION_LEDGERS', N'U') AND name = N'IX_TRANSACTION_LEDGERS_IsDeleted')
BEGIN
    CREATE INDEX [IX_TRANSACTION_LEDGERS_IsDeleted] ON [dbo].[TRANSACTION_LEDGERS] ([IsDeleted]);
END