IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYOUT_LINE_ITEMS_SELLER_PAYOUTS_PAYOUT_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYOUT_LINE_ITEMS'))
BEGIN
    ALTER TABLE [dbo].[PAYOUT_LINE_ITEMS] ADD CONSTRAINT [FK_PAYOUT_LINE_ITEMS_SELLER_PAYOUTS_PAYOUT_ID] FOREIGN KEY ([PAYOUT_ID]) REFERENCES [dbo].[SELLER_PAYOUTS] ([ID]);
END