IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TRANSACTION_LEDGERS', N'U') AND name = N'IX_TRANSACTION_LEDGERS_REFERENCE_ID')
BEGIN
    CREATE INDEX [IX_TRANSACTION_LEDGERS_REFERENCE_ID] ON [dbo].[TRANSACTION_LEDGERS] ([REFERENCE_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TRANSACTION_LEDGERS', N'U') AND name = N'IX_TRANSACTION_LEDGERS_SELLER_ID_TRANSACTION_DATE')
BEGIN
    CREATE INDEX [IX_TRANSACTION_LEDGERS_SELLER_ID_TRANSACTION_DATE] ON [dbo].[TRANSACTION_LEDGERS] ([SELLER_ID], [TRANSACTION_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TRANSACTION_LEDGERS', N'U') AND name = N'IX_TRANSACTION_LEDGERS_SELLER_ID_TRANSACTION_TYPE')
BEGIN
    CREATE INDEX [IX_TRANSACTION_LEDGERS_SELLER_ID_TRANSACTION_TYPE] ON [dbo].[TRANSACTION_LEDGERS] ([SELLER_ID], [TRANSACTION_TYPE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.TRANSACTION_LEDGERS', N'U') AND name = N'IX_TRANSACTION_LEDGERS_TRANSACTION_TYPE')
BEGIN
    CREATE INDEX [IX_TRANSACTION_LEDGERS_TRANSACTION_TYPE] ON [dbo].[TRANSACTION_LEDGERS] ([TRANSACTION_TYPE]);
END