IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYOUT_LINE_ITEMS', N'U') AND name = N'IX_PAYOUT_LINE_ITEMS_IsDeleted')
BEGIN
    CREATE INDEX [IX_PAYOUT_LINE_ITEMS_IsDeleted] ON [dbo].[PAYOUT_LINE_ITEMS] ([IsDeleted]);
END