IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_COMMISSION_MODEL_ID_SELLER_ID')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_COMMISSION_MODEL_ID_SELLER_ID] ON [dbo].[COMMISSION_ENTRIES] ([COMMISSION_MODEL_ID], [SELLER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_ORDER_ID')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_ORDER_ID] ON [dbo].[COMMISSION_ENTRIES] ([ORDER_ID]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_SELLER_ID_CALCULATED_DATE')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_SELLER_ID_CALCULATED_DATE] ON [dbo].[COMMISSION_ENTRIES] ([SELLER_ID], [CALCULATED_DATE]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_SELLER_ID_STATUS')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_SELLER_ID_STATUS] ON [dbo].[COMMISSION_ENTRIES] ([SELLER_ID], [STATUS]);
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_STATUS')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_STATUS] ON [dbo].[COMMISSION_ENTRIES] ([STATUS]);
END