IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.PAYOUT_REPORTS', N'U') AND name = N'IX_PAYOUT_REPORTS_PAYOUT_PERIOD_ID')
BEGIN
    CREATE INDEX [IX_PAYOUT_REPORTS_PAYOUT_PERIOD_ID] ON [dbo].[PAYOUT_REPORTS] ([PAYOUT_PERIOD_ID]);
END