IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.FINANCIAL_ADJUSTMENTS', N'U') AND name = N'IX_FINANCIAL_ADJUSTMENTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_FINANCIAL_ADJUSTMENTS_IsDeleted] ON [dbo].[FINANCIAL_ADJUSTMENTS] ([IsDeleted]);
END