IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.SELLER_PAYOUTS', N'U') AND name = N'IX_SELLER_PAYOUTS_IsDeleted')
BEGIN
    CREATE INDEX [IX_SELLER_PAYOUTS_IsDeleted] ON [dbo].[SELLER_PAYOUTS] ([IsDeleted]);
END