IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_PAYOUT_REPORTS_PAYOUT_PERIODS_PAYOUT_PERIOD_ID' AND parent_object_id = OBJECT_ID(N'dbo.PAYOUT_REPORTS'))
BEGIN
    ALTER TABLE [dbo].[PAYOUT_REPORTS] ADD CONSTRAINT [FK_PAYOUT_REPORTS_PAYOUT_PERIODS_PAYOUT_PERIOD_ID] FOREIGN KEY ([PAYOUT_PERIOD_ID]) REFERENCES [dbo].[PAYOUT_PERIODS] ([ID]);
END