IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.COMMISSION_ENTRIES', N'U') AND name = N'IX_COMMISSION_ENTRIES_IsDeleted')
BEGIN
    CREATE INDEX [IX_COMMISSION_ENTRIES_IsDeleted] ON [dbo].[COMMISSION_ENTRIES] ([IsDeleted]);
END