// <auto-generated>
// QuickCode — DO NOT EDIT (quickcode-controlled scaffold)
// This file is overwritten on full template regen. Add user logic in separate .cs files.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System.Security.Cryptography;
using System.Text;
using System.Diagnostics;
using Dapper;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;

namespace QuickCode.Demo.Domain.Shared.Abstractions.Data;

public sealed class QuickCodeSeedDataRunner(
    IDbConnectionFactory connectionFactory,
    IConfiguration configuration,
    ILogger<QuickCodeSeedDataRunner> logger)
{
    private const string HistoryTableName = "__QuickCodeSeedHistory";
    private const int MaxBatchRows = 100;
    private const int TargetMaxParametersPerBatch = 1800;

    private static readonly Dictionary<string, string[]> UniqueColumnMap = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Modules"] = ["Name"],
        ["Models"] = ["Name", "ModuleName"],
        ["ApiMethodDefinitions"] = ["Key"],
        ["PortalPageDefinitions"] = ["Key"],
        ["ApiMethodAccessGrants"] = ["ApiMethodDefinitionKey", "PermissionGroupName"],
        ["PortalPageAccessGrants"] = ["PortalPageDefinitionKey", "PermissionGroupName", "PageAction"],
        ["PortalMenus"] = ["Key"],
        ["TableComboboxSettings"] = ["TableName", "IdColumn"],
        // Identity PK: seed JSON omits Id so SQL Server assigns values; dedupe by natural key.
        ["ColumnTypes"] = ["TypeName"]
    };

    public async Task SeedAsync(CancellationToken cancellationToken = default)
    {
        var totalStopwatch = Stopwatch.StartNew();
        var databaseType = configuration.GetSection("AppSettings:DatabaseType").Get<string>();
        if (string.IsNullOrWhiteSpace(databaseType) ||
            databaseType.Equals("inMemory", StringComparison.OrdinalIgnoreCase))
            return;

        var files = FindSeedFiles().ToList();
        if (files.Count == 0)
        {
            logger.LogInformation("No QuickCode seed data files found.");
            return;
        }

        await using var connection = await connectionFactory.CreateWriteConnectionAsync(cancellationToken);
        await connection.ExecuteAsync(CreateHistoryTableSql(databaseType));

        foreach (var file in files)
        {
            var fileStopwatch = Stopwatch.StartNew();
            var content = await File.ReadAllTextAsync(file, cancellationToken);
            var fileName = Path.GetFileName(file);
            var hash = Hash(content);
            var alreadyApplied = await connection.ExecuteScalarAsync<int>(
                SelectHistoryCountSql(databaseType),
                new { SeedFile = fileName, ScriptHash = hash });

            if (alreadyApplied > 0)
            {
                logger.LogInformation("Skipped QuickCode seed file {SeedFile}; already applied. Elapsed: {ElapsedMs} ms.", fileName, fileStopwatch.ElapsedMilliseconds);
                continue;
            }

            await using var transaction = await connection.BeginTransactionAsync(cancellationToken);
            var insertedRows = await ApplySeedFileAsync(connection, transaction, databaseType, content, logger);
            await connection.ExecuteAsync(InsertHistorySql(databaseType), new
            {
                SeedFile = fileName,
                ScriptHash = hash,
                AppliedAtUtc = DateTime.UtcNow,
                InsertedRows = insertedRows,
                ElapsedMs = fileStopwatch.ElapsedMilliseconds
            }, transaction);
            await transaction.CommitAsync(cancellationToken);

            logger.LogInformation("Applied QuickCode seed file {SeedFile}; inserted {InsertedRows} row(s) in {ElapsedMs} ms.", fileName, insertedRows, fileStopwatch.ElapsedMilliseconds);
        }

        logger.LogInformation("QuickCode seed completed. Files scanned: {FileCount}, elapsed: {ElapsedMs} ms.", files.Count, totalStopwatch.ElapsedMilliseconds);
    }

    private static async Task<int> ApplySeedFileAsync(
        System.Data.Common.DbConnection connection,
        System.Data.Common.DbTransaction transaction,
        string databaseType,
        string content,
        ILogger logger)
    {
        var root = JObject.Parse(content).ToObject<Dictionary<string, List<Dictionary<string, object?>>>>();
        if (root is null)
            return 0;

        var insertedRows = 0;
        foreach (var (tableName, rows) in root)
        {
            var tableStopwatch = Stopwatch.StartNew();
            var uniqueColumns = ResolveUniqueColumns(tableName, rows);
            var existingKeys = await LoadExistingKeysAsync(connection, transaction, databaseType, tableName, uniqueColumns);
            var insertedInTable = 0;
            var rowsToInsert = new List<Dictionary<string, object?>>(rows.Count);

            foreach (var row in rows)
            {
                var normalized = NormalizeRow(row);
                if (normalized.Count == 0)
                    continue;

                var rowKey = BuildRowKey(normalized, uniqueColumns);
                if (existingKeys.Contains(rowKey))
                    continue;

                rowsToInsert.Add(normalized);
                existingKeys.Add(rowKey);
                insertedRows++;
                insertedInTable++;
            }

            if (rowsToInsert.Count > 0)
            {
                var batchSize = GetBatchSize(rowsToInsert[0].Count);
                foreach (var batch in ChunkRows(rowsToInsert, batchSize))
                {
                    var (batchSql, batchParameters) = BuildInsertBatchSql(databaseType, tableName, batch);
                    await connection.ExecuteAsync(batchSql, batchParameters, transaction);
                }
            }

            var skippedInTable = rows.Count - insertedInTable;
            if (tableStopwatch.ElapsedMilliseconds > 250 || insertedInTable > 0)
            {
                // Log potentially expensive table processing with counts for easier diagnosis.
                logger.LogInformation(
                    "QuickCode seed table {TableName}: inserted {InsertedRows}, skipped {SkippedRows}, elapsed: {ElapsedMs} ms.",
                    tableName,
                    insertedInTable,
                    skippedInTable,
                    tableStopwatch.ElapsedMilliseconds);
            }
        }

        return insertedRows;
    }

    private static string[] ResolveUniqueColumns(
        string tableName,
        List<Dictionary<string, object?>> rows)
    {
        var mapped = UniqueColumnMap.GetValueOrDefault(tableName);
        if (mapped is not null)
            return mapped;

        var firstRow = rows.FirstOrDefault();
        if (firstRow is null)
            return [];

        var normalizedKeys = NormalizeRow(firstRow).Keys.ToArray();
        var idColumn = normalizedKeys.FirstOrDefault(key =>
            key.Equals("Id", StringComparison.OrdinalIgnoreCase) ||
            key.Equals($"{tableName}Id", StringComparison.OrdinalIgnoreCase));
        if (!string.IsNullOrWhiteSpace(idColumn))
            return [idColumn];

        var keyColumn = normalizedKeys.FirstOrDefault(key => key.Equals("Key", StringComparison.OrdinalIgnoreCase));
        if (!string.IsNullOrWhiteSpace(keyColumn))
            return [keyColumn];

        var nameColumn = normalizedKeys.FirstOrDefault(key => key.Equals("Name", StringComparison.OrdinalIgnoreCase));
        if (!string.IsNullOrWhiteSpace(nameColumn))
            return [nameColumn];

        return normalizedKeys;
    }

    private static async Task<HashSet<string>> LoadExistingKeysAsync(
        System.Data.Common.DbConnection connection,
        System.Data.Common.DbTransaction transaction,
        string databaseType,
        string tableName,
        string[] uniqueColumns)
    {
        if (uniqueColumns.Length == 0)
            return [];

        var selectColumns = string.Join(", ", uniqueColumns.Select(column => Quote(column, databaseType)));
        var sql = $"SELECT {selectColumns} FROM {Quote(tableName, databaseType)};";
        var records = await connection.QueryAsync(sql, transaction: transaction);
        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (var record in records)
        {
            if (record is not IDictionary<string, object?> values)
                continue;

            var key = string.Join("|", uniqueColumns.Select(column =>
            {
                var value = values.TryGetValue(column, out var exact)
                    ? exact
                    : values.FirstOrDefault(pair => string.Equals(pair.Key, column, StringComparison.OrdinalIgnoreCase)).Value;
                return value?.ToString() ?? "<null>";
            }));
            keys.Add(key);
        }

        return keys;
    }

    private static string BuildRowKey(Dictionary<string, object?> row, string[] uniqueColumns) =>
        string.Join("|", uniqueColumns.Select(column => row.TryGetValue(column, out var value) ? value?.ToString() ?? "<null>" : "<missing>"));

    private static Dictionary<string, object?> NormalizeRow(Dictionary<string, object?> row)
    {
        return row.ToDictionary(
            pair => pair.Key,
            pair => pair.Value switch
            {
                JValue value => value.Value,
                JToken token => token.ToString(Newtonsoft.Json.Formatting.None),
                _ => pair.Value
            },
            StringComparer.OrdinalIgnoreCase);
    }

    private static int GetBatchSize(int columnCount)
    {
        if (columnCount <= 0)
            return 1;

        var safeByParameters = Math.Max(1, TargetMaxParametersPerBatch / columnCount);
        return Math.Max(1, Math.Min(MaxBatchRows, safeByParameters));
    }

    private static IEnumerable<List<Dictionary<string, object?>>> ChunkRows(
        List<Dictionary<string, object?>> rows,
        int batchSize)
    {
        for (var i = 0; i < rows.Count; i += batchSize)
        {
            yield return rows.GetRange(i, Math.Min(batchSize, rows.Count - i));
        }
    }

    private static (string Sql, DynamicParameters Parameters) BuildInsertBatchSql(
        string databaseType,
        string tableName,
        List<Dictionary<string, object?>> rows)
    {
        if (rows.Count == 0)
            throw new ArgumentException("Batch cannot be empty.", nameof(rows));

        var columnList = rows[0].Keys.ToList();
        var names = string.Join(", ", columnList.Select(column => Quote(column, databaseType)));
        var parameters = new DynamicParameters();
        var valueRows = new List<string>(rows.Count);

        for (var rowIndex = 0; rowIndex < rows.Count; rowIndex++)
        {
            var row = rows[rowIndex];
            var rowParameterNames = new List<string>(columnList.Count);
            for (var colIndex = 0; colIndex < columnList.Count; colIndex++)
            {
                var column = columnList[colIndex];
                var parameterName = $"p_{rowIndex}_{colIndex}";
                rowParameterNames.Add("@" + parameterName);
                parameters.Add(parameterName, row.TryGetValue(column, out var value) ? value : null);
            }

            valueRows.Add($"({string.Join(", ", rowParameterNames)})");
        }

        var sql = $"INSERT INTO {Quote(tableName, databaseType)} ({names}) VALUES {string.Join(", ", valueRows)};";
        return (sql, parameters);
    }

    private static IEnumerable<string> FindSeedFiles()
    {
        var baseDirectory = AppContext.BaseDirectory;
        if (!Directory.Exists(baseDirectory))
            return [];

        return Directory
            .GetFiles(baseDirectory, "*.json", SearchOption.AllDirectories)
            .Where(path => path.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
                .Any(part => part.Equals("InitialData", StringComparison.OrdinalIgnoreCase)))
            .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
            .ThenBy(path => path, StringComparer.OrdinalIgnoreCase);
    }

    private static string CreateHistoryTableSql(string databaseType) => databaseType.ToLowerInvariant() switch
    {
        "mssql" => $"""
                   IF OBJECT_ID(N'dbo.{HistoryTableName}', N'U') IS NULL
                   BEGIN
                       CREATE TABLE [dbo].[{HistoryTableName}] (
                           [SeedFile] nvarchar(300) NOT NULL,
                           [ScriptHash] nvarchar(128) NOT NULL,
                           [AppliedAtUtc] datetime2 NOT NULL,
                           [InsertedRows] int NOT NULL,
                           [ElapsedMs] bigint NOT NULL,
                           CONSTRAINT [PK_{HistoryTableName}] PRIMARY KEY ([SeedFile], [ScriptHash])
                       );
                   END;
                   IF COL_LENGTH(N'dbo.{HistoryTableName}', N'ElapsedMs') IS NULL
                   BEGIN
                       ALTER TABLE [dbo].[{HistoryTableName}] ADD [ElapsedMs] bigint NOT NULL CONSTRAINT [DF_{HistoryTableName}_ElapsedMs] DEFAULT (0);
                   END;
                   """,
        "postgresql" => $"""
                        CREATE TABLE IF NOT EXISTS "{HistoryTableName}" (
                            "SeedFile" varchar(300) NOT NULL,
                            "ScriptHash" varchar(128) NOT NULL,
                            "AppliedAtUtc" timestamp with time zone NOT NULL,
                            "InsertedRows" integer NOT NULL,
                            "ElapsedMs" bigint NOT NULL DEFAULT 0,
                            CONSTRAINT "PK_{HistoryTableName}" PRIMARY KEY ("SeedFile", "ScriptHash")
                        );
                        ALTER TABLE "{HistoryTableName}" ADD COLUMN IF NOT EXISTS "ElapsedMs" bigint NOT NULL DEFAULT 0;
                        """,
        "mysql" => $"""
                   CREATE TABLE IF NOT EXISTS `{HistoryTableName}` (
                       `SeedFile` varchar(300) NOT NULL,
                       `ScriptHash` varchar(128) NOT NULL,
                       `AppliedAtUtc` datetime(6) NOT NULL,
                       `InsertedRows` int NOT NULL,
                       `ElapsedMs` bigint NOT NULL DEFAULT 0,
                       CONSTRAINT `PK_{HistoryTableName}` PRIMARY KEY (`SeedFile`, `ScriptHash`)
                   );
                   ALTER TABLE `{HistoryTableName}` ADD COLUMN IF NOT EXISTS `ElapsedMs` bigint NOT NULL DEFAULT 0;
                   """,
        _ => throw new NotSupportedException($"Database type '{databaseType}' is not supported.")
    };

    private static string SelectHistoryCountSql(string databaseType) => databaseType.ToLowerInvariant() switch
    {
        "mssql" => $"SELECT COUNT(*) FROM [dbo].[{HistoryTableName}] WHERE [SeedFile] = @SeedFile AND [ScriptHash] = @ScriptHash;",
        "postgresql" => $"SELECT COUNT(*) FROM \"{HistoryTableName}\" WHERE \"SeedFile\" = @SeedFile AND \"ScriptHash\" = @ScriptHash;",
        "mysql" => $"SELECT COUNT(*) FROM `{HistoryTableName}` WHERE `SeedFile` = @SeedFile AND `ScriptHash` = @ScriptHash;",
        _ => throw new NotSupportedException($"Database type '{databaseType}' is not supported.")
    };

    private static string InsertHistorySql(string databaseType) => databaseType.ToLowerInvariant() switch
    {
        "mssql" => $"INSERT INTO [dbo].[{HistoryTableName}] ([SeedFile], [ScriptHash], [AppliedAtUtc], [InsertedRows], [ElapsedMs]) VALUES (@SeedFile, @ScriptHash, @AppliedAtUtc, @InsertedRows, @ElapsedMs);",
        "postgresql" => $"INSERT INTO \"{HistoryTableName}\" (\"SeedFile\", \"ScriptHash\", \"AppliedAtUtc\", \"InsertedRows\", \"ElapsedMs\") VALUES (@SeedFile, @ScriptHash, @AppliedAtUtc, @InsertedRows, @ElapsedMs);",
        "mysql" => $"INSERT INTO `{HistoryTableName}` (`SeedFile`, `ScriptHash`, `AppliedAtUtc`, `InsertedRows`, `ElapsedMs`) VALUES (@SeedFile, @ScriptHash, @AppliedAtUtc, @InsertedRows, @ElapsedMs);",
        _ => throw new NotSupportedException($"Database type '{databaseType}' is not supported.")
    };

    private static string Quote(string identifier, string databaseType) => databaseType.ToLowerInvariant() switch
    {
        "mssql" => $"[{identifier.Replace("]", "]]", StringComparison.Ordinal)}]",
        "postgresql" => $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"",
        "mysql" => $"`{identifier.Replace("`", "``", StringComparison.Ordinal)}`",
        _ => identifier
    };

    private static string Hash(string value)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(value));
        return Convert.ToHexString(bytes);
    }
}
