// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuickCode.Demo.OrderManagementModule.Domain.Enums;

public enum ReturnStatus{
	[Description("Return request submitted")]
	Requested,
	[Description("Return request approved")]
	Approved,
	[Description("Return request rejected")]
	Rejected,
	[Description("Item shipped back by customer")]
	ShippedByCustomer,
	[Description("Returned item received by seller")]
	Received,
	[Description("Return process is complete")]
	Completed
}
