// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using QuickCode.Demo.Infrastructure.Integration.Nswag.Clients.PricingEngineModuleApi.Contracts;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Portal.Helpers;

namespace QuickCode.Demo.Portal.Models.PricingEngineModule
{
    public class CommissionRuleData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public string SelectedKey { get; set; }
        public CommissionRuleDto SelectedItem { get; set; }
        public List<CommissionRuleDto> List { get; set; }
    }

    public static partial class CommissionRuleExtensions
    {
        public static string GetKey(this CommissionRuleDto dto)
        {
            return $"{dto.Id}";
        }
    }

    public class CommissionRuleGetActiveRulesByModelData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public int CommissionRuleCommissionModelId { get; set; }
        public List<dynamic> List { get; set; } = new();
    }

    public class CommissionRuleGetByModelIdData : BaseComboBoxModel
    {
        public int TotalPage { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int NumberOfRecord { get; set; }
        public bool HasRun { get; set; }
        public string ErrorMessage { get; set; }
        public int? QueryHttpStatus { get; set; }
        /// <summary>True when total row count is unknown and another page may exist.</summary>
        public bool HasMoreRecords { get; set; }
        public int CommissionRuleCommissionModelId { get; set; }
        public List<dynamic> List { get; set; } = new();
    }
}