// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.PayoutPeriod;
using QuickCode.Demo.FinanceSettlementModule.Application.Mappings;
using QuickCode.Demo.FinanceSettlementModule.Persistence.Sql;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Persistence.Repositories
{
    public partial class PayoutPeriodRepository : BaseRepository, IPayoutPeriodRepository
    {
        public async Task<RepoResponse<int>> ClosePeriodAsync(int payoutPeriodId, ClosePeriodRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(PayoutPeriodCrudSqlBindings.OperationNames.ClosePeriod, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PayoutPeriod.Command.ClosePeriod);
                var parameters = new
                {
                    PRM_PAYOUT_PERIOD_ID = payoutPeriodId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}