-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 CCO.[COMMISSION_MODEL_ID], CCO.[EFFECTIVE_DATE] 
FROM [CATEGORY_COMMISSION_OVERRIDES] CCO 
WHERE CCO.[IsDeleted] = 0 
	AND CCO.[CATEGORY_ID] = @PRM_CATEGORY_COMMISSION_OVERRIDE_CATEGORY_ID 
ORDER BY CCO.[ID] 