// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.PayoutReport;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.PayoutReport
{
    public class UpdatePayoutReportCommand : IRequest<Response<bool>>
    {
        public int Id { get; set; }
        public PayoutReportDto request { get; set; }

        public UpdatePayoutReportCommand(int id, PayoutReportDto request)
        {
            this.request = request;
            this.Id = id;
        }

        public class UpdatePayoutReportHandler : IRequestHandler<UpdatePayoutReportCommand, Response<bool>>
        {
            private readonly ILogger<UpdatePayoutReportHandler> _logger;
            private readonly IPayoutReportRepository _repository;
            public UpdatePayoutReportHandler(ILogger<UpdatePayoutReportHandler> logger, IPayoutReportRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<bool>> Handle(UpdatePayoutReportCommand request, CancellationToken cancellationToken)
            {
                var updateItem = await _repository.GetByPkAsync(request.Id);
                if (updateItem.Code == 404)
                    return Response<bool>.NotFound();
                var model = request.request;
                var returnValue = await _repository.UpdateAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}