-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS COUNT,
	SUM(SP.[NET_PAYOUT_AMOUNT]) AS TOTAL_AMOUNT 
FROM [SELLER_PAYOUTS] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[STATUS] = 'Pending' 