-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 COUNT(*) AS PAID_COUNT,
	SUM(SP.[NET_PAYOUT_AMOUNT]) AS PAID_AMOUNT 
FROM [SELLER_PAYOUTS] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[STATUS] = 'Paid' 
	AND SP.[PAID_DATE] > DATEADD(DAY, -30,
	GETDATE()) 