// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CommissionModel;
using CommissionModelEntity = QuickCode.Demo.PricingEngineModule.Domain.Entities.CommissionModel;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Mappings
{
    public static class CommissionModelMappings
    {
        public static List<CommissionModelDto> ToDto(this IEnumerable<CommissionModelEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CommissionModelDto ToDto(this CommissionModelEntity model)
        {
            return new CommissionModelDto
            {
                Id = model.Id,
                Name = model.Name,
                IsActive = model.IsActive,
                Description = model.Description
            };
        }

        public static CommissionModelEntity ToEntity(this CommissionModelDto model)
        {
            return new CommissionModelEntity
            {
                Id = model.Id,
                Name = model.Name,
                IsActive = model.IsActive,
                Description = model.Description
            };
        }
    }
}