// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.ProductVariant;
using ProductVariantEntity = QuickCode.Demo.ProductCatalogModule.Domain.Entities.ProductVariant;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Application.Mappings
{
    public static class ProductVariantMappings
    {
        public static List<ProductVariantDto> ToDto(this IEnumerable<ProductVariantEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductVariantDto ToDto(this ProductVariantEntity model)
        {
            return new ProductVariantDto
            {
                Id = model.Id,
                ProductId = model.ProductId,
                Sku = model.Sku,
                Price = model.Price,
                StockQuantity = model.StockQuantity,
                IsActive = model.IsActive
            };
        }

        public static ProductVariantEntity ToEntity(this ProductVariantDto model)
        {
            return new ProductVariantEntity
            {
                Id = model.Id,
                ProductId = model.ProductId,
                Sku = model.Sku,
                Price = model.Price,
                StockQuantity = model.StockQuantity,
                IsActive = model.IsActive
            };
        }
    }
}