// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QcEntity = global::QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CategoryCommissionOverride;
using QuickCode.Demo.PricingEngineModule.Application.Mappings;
using QuickCode.Demo.PricingEngineModule.Persistence.Sql;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Persistence.Repositories
{
    public partial class CategoryCommissionOverrideRepository : BaseRepository, ICategoryCommissionOverrideRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public CategoryCommissionOverrideRepository(ILogger<CategoryCommissionOverrideRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "CategoryCommissionOverride")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<CategoryCommissionOverrideDto>> InsertAsync(CategoryCommissionOverrideDto value)
        {
            return await ExecuteWithExceptionHandling(CategoryCommissionOverrideCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CategoryCommissionOverride.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(CategoryCommissionOverrideCrudSqlBindings.ParameterNamePrefix, value, CategoryCommissionOverrideCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.CategoryCommissionOverride>(sql, p);
                return new RepoResponse<CategoryCommissionOverrideDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CategoryCommissionOverrideDto value)
        {
            return await ExecuteWithExceptionHandling(CategoryCommissionOverrideCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CategoryCommissionOverride.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(CategoryCommissionOverrideCrudSqlBindings.ParameterNamePrefix, value, CategoryCommissionOverrideCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CategoryCommissionOverrideDto value)
        {
            return await ExecuteWithExceptionHandling(CategoryCommissionOverrideCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CategoryCommissionOverride.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(CategoryCommissionOverrideCrudSqlBindings.ParameterNamePrefix, value, CategoryCommissionOverrideCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<CategoryCommissionOverrideDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(CategoryCommissionOverrideCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CategoryCommissionOverride.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(CategoryCommissionOverrideCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.CategoryCommissionOverride>(sql, p);
                return row == null ? CreateNotFoundResponse<CategoryCommissionOverrideDto>("Not found in CategoryCommissionOverride") : new RepoResponse<CategoryCommissionOverrideDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<CategoryCommissionOverrideDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(CategoryCommissionOverrideCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CategoryCommissionOverrideDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.CategoryCommissionOverride.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.CategoryCommissionOverride>(sql, p);
                return new RepoResponse<List<CategoryCommissionOverrideDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(CategoryCommissionOverrideCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CategoryCommissionOverride.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}