-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 S.[ID], S.[SELLER_ID], S.[NAME] 
FROM [STORES] S 
WHERE S.[IsDeleted] = 0 
	AND S.[SLUG] = @PRM_STORE_SLUG 
ORDER BY S.[ID] 