services:
  demo-pg-data:
    container_name: "demo-pg-data"
    image: postgres:18

  demo-sql-data:
    container_name: "demo-sql-data"
    image: mcr.microsoft.com/mssql/server:2025-latest
    
  demo-mysql-data:
    container_name: "demo-mysql-data"
    image: mysql:8.3

  demo-elasticsearch:
    container_name: demo-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0

  demo-kibana:
    container_name: demo-kibana
    image: docker.elastic.co/kibana/kibana:8.11.0

  quickcode-demo-gateway-api:
    container_name: "quickcode-demo-gateway-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-gateway-api
    build:
      context: .
      dockerfile: Presentation/QuickCode.Demo.Gateway/Dockerfile

  quickcode-demo-identity-module-api:
    container_name: "quickcode-demo-identity-module-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-identity-module-api
    build:
      context: . 
      dockerfile: Modules/IdentityModule/Presentation/QuickCode.Demo.IdentityModule.Api/Dockerfile
    depends_on:
      demo-sql-data:
        condition: service_healthy
      demo-pg-data:
        condition: service_started
      

  quickcode-demo-finance-settlement-module-api:
    container_name: "quickcode-demo-finance-settlement-module-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-finance-settlement-module-api
    build:
      context: . 
      dockerfile: Modules/FinanceSettlementModule/Presentation/QuickCode.Demo.FinanceSettlementModule.Api/Dockerfile
    depends_on:
      demo-sql-data:
        condition: service_healthy
      demo-pg-data:
        condition: service_started
      

  quickcode-demo-order-management-module-api:
    container_name: "quickcode-demo-order-management-module-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-order-management-module-api
    build:
      context: . 
      dockerfile: Modules/OrderManagementModule/Presentation/QuickCode.Demo.OrderManagementModule.Api/Dockerfile
    depends_on:
      demo-sql-data:
        condition: service_healthy
      demo-pg-data:
        condition: service_started
      

  quickcode-demo-pricing-engine-module-api:
    container_name: "quickcode-demo-pricing-engine-module-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-pricing-engine-module-api
    build:
      context: . 
      dockerfile: Modules/PricingEngineModule/Presentation/QuickCode.Demo.PricingEngineModule.Api/Dockerfile
    depends_on:
      demo-sql-data:
        condition: service_healthy
      demo-pg-data:
        condition: service_started
      

  quickcode-demo-product-catalog-module-api:
    container_name: "quickcode-demo-product-catalog-module-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-product-catalog-module-api
    build:
      context: . 
      dockerfile: Modules/ProductCatalogModule/Presentation/QuickCode.Demo.ProductCatalogModule.Api/Dockerfile
    depends_on:
      demo-sql-data:
        condition: service_healthy
      demo-pg-data:
        condition: service_started
      

  quickcode-demo-seller-management-module-api:
    container_name: "quickcode-demo-seller-management-module-api"
    image: ${DOCKER_REGISTRY-}quickcode-demo-seller-management-module-api
    build:
      context: . 
      dockerfile: Modules/SellerManagementModule/Presentation/QuickCode.Demo.SellerManagementModule.Api/Dockerfile
    depends_on:
      demo-sql-data:
        condition: service_healthy
      demo-pg-data:
        condition: service_started
      

#[-WEB-]
  
  demo-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: demo-zookeeper
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  demo-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: demo-kafka
    depends_on:
      - demo-zookeeper
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: demo-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://demo-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  demo-kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: demo-kafdrop
    ports:
      - "${KAFDROP_PORT:-9000}:9000"
    depends_on:
      - demo-kafka
    environment:
      KAFKA_BROKERCONNECT: demo-kafka:9092
        
  quickcode-demo-portal:
    container_name: "quickcode-demo-portal"
    image: ${DOCKER_REGISTRY-}quickcode-demo-portal
    build:
      context: .
      dockerfile: Presentation/QuickCode.Demo.Portal/Dockerfile
      
  quickcode-demo-event-listener-service:
    container_name: "quickcode-demo-event-listener-service"
    image: ${DOCKER_REGISTRY-}quickcode-demo-event-listener-service
    build:
      context: .
      dockerfile: Services/QuickCode.Demo.EventListenerService/Dockerfile
