// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Demo.FinanceSettlementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class CommissionRule
    {
        public static class Command
        {
            private const string _prefix = "FinanceSettlementModule.CommissionRule.Command";
            private const string _sqlScriptStem = "CommissionRule";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string Deactivate => ResourceKey($"{_sqlScriptStem}.Deactivate.g.sql");
            public static string UpdateRule => ResourceKey($"{_sqlScriptStem}.UpdateRule.g.sql");
        }
    }
}