-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
UPDATE [dbo].[SELLER_TIERS]
SET
    [NAME] = @PRM_SELLER_TIER_NAME,
    [MIN_SALES_VOLUME] = @PRM_SELLER_TIER_MIN_SALES_VOLUME,
    [BENEFITS_DESCRIPTION] = @PRM_SELLER_TIER_BENEFITS_DESCRIPTION
WHERE
    [ID] = @PRM_SELLER_TIER_ID
    AND [IsDeleted] = 0;