// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using QuickCode.Demo.PricingEngineModule.Domain;
using QuickCode.Demo.Domain.Shared.Abstractions;
using QuickCode.Demo.Domain.Shared.Entities;

namespace QuickCode.Demo.PricingEngineModule.Domain.Entities;

[Table("SELLER_COMMISSION_ASSIGNMENTS")]
public partial class SellerCommissionAssignment : IAuditableEntity 
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.None)]
	[Column("SELLER_ID")]
	public int SellerId { get; set; }
	
	[Column("COMMISSION_MODEL_ID")]
	public int CommissionModelId { get; set; }
	
	[Column("EFFECTIVE_DATE")]
	public DateTime EffectiveDate { get; set; }
	
	[ForeignKey("CommissionModelId")]
	[InverseProperty(nameof(CommissionModel.SellerCommissionAssignments))]
	public virtual CommissionModel CommissionModel { get; set; } = null!;
}

