// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.Order;
using OrderEntity = QuickCode.Demo.OrderManagementModule.Domain.Entities.Order;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Mappings
{
    public static class OrderMappings
    {
        public static List<OrderDto> ToDto(this IEnumerable<OrderEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OrderDto ToDto(this OrderEntity model)
        {
            return new OrderDto
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                SellerId = model.SellerId,
                OrderNumber = model.OrderNumber,
                TotalAmount = model.TotalAmount,
                ShippingAddress = model.ShippingAddress,
                Status = model.Status,
                OrderDate = model.OrderDate
            };
        }

        public static OrderEntity ToEntity(this OrderDto model)
        {
            return new OrderEntity
            {
                Id = model.Id,
                CustomerId = model.CustomerId,
                SellerId = model.SellerId,
                OrderNumber = model.OrderNumber,
                TotalAmount = model.TotalAmount,
                ShippingAddress = model.ShippingAddress,
                Status = model.Status,
                OrderDate = model.OrderDate
            };
        }
    }
}