// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.OrderManagementModule.Application.Dtos.ReturnRequest;
using ReturnRequestEntity = QuickCode.Demo.OrderManagementModule.Domain.Entities.ReturnRequest;
using QuickCode.Demo.OrderManagementModule.Domain.Enums;

namespace QuickCode.Demo.OrderManagementModule.Application.Mappings
{
    public static class ReturnRequestMappings
    {
        public static List<ReturnRequestDto> ToDto(this IEnumerable<ReturnRequestEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ReturnRequestDto ToDto(this ReturnRequestEntity model)
        {
            return new ReturnRequestDto
            {
                Id = model.Id,
                OrderId = model.OrderId,
                OrderItemId = model.OrderItemId,
                Reason = model.Reason,
                Status = model.Status,
                RequestedDate = model.RequestedDate,
                UpdatedDate = model.UpdatedDate
            };
        }

        public static ReturnRequestEntity ToEntity(this ReturnRequestDto model)
        {
            return new ReturnRequestEntity
            {
                Id = model.Id,
                OrderId = model.OrderId,
                OrderItemId = model.OrderItemId,
                Reason = model.Reason,
                Status = model.Status,
                RequestedDate = model.RequestedDate,
                UpdatedDate = model.UpdatedDate
            };
        }
    }
}