// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QcEntity = global::QuickCode.Demo.SellerManagementModule.Domain.Entities;
using QuickCode.Demo.SellerManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.SellerManagementModule.Application.Dtos.SellerTier;
using QuickCode.Demo.SellerManagementModule.Application.Mappings;
using QuickCode.Demo.SellerManagementModule.Persistence.Sql;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Persistence.Repositories
{
    public partial class SellerTierRepository : BaseRepository, ISellerTierRepository
    {
        private readonly IDbConnectionFactory _connectionFactory;
        public SellerTierRepository(ILogger<SellerTierRepository> logger, IDbConnectionFactory connectionFactory) : base(logger, "SellerTier")
        {
            _connectionFactory = connectionFactory;
        }

        public async Task<RepoResponse<SellerTierDto>> InsertAsync(SellerTierDto value)
        {
            return await ExecuteWithExceptionHandling(SellerTierCrudSqlBindings.OperationNames.Insert, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerTier.Crud.Insert);
                var p = CrudDapperParameterBinder.FromDto(SellerTierCrudSqlBindings.ParameterNamePrefix, value, SellerTierCrudSqlBindings.Insert);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var inserted = await connection.QuerySingleAsync<QcEntity.SellerTier>(sql, p);
                return new RepoResponse<SellerTierDto>(inserted.ToDto());
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(SellerTierDto value)
        {
            return await ExecuteWithExceptionHandling(SellerTierCrudSqlBindings.OperationNames.Update, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerTier.Crud.Update);
                var p = CrudDapperParameterBinder.FromDto(SellerTierCrudSqlBindings.ParameterNamePrefix, value, SellerTierCrudSqlBindings.Update);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(SellerTierDto value)
        {
            return await ExecuteWithExceptionHandling(SellerTierCrudSqlBindings.OperationNames.Delete, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerTier.Crud.Delete);
                var p = CrudDapperParameterBinder.FromDto(SellerTierCrudSqlBindings.ParameterNamePrefix, value, SellerTierCrudSqlBindings.Delete);
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var affected = await connection.ExecuteAsync(sql, p);
                return new RepoResponse<bool>(affected > 0);
            });
        }

        public async Task<RepoResponse<SellerTierDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling(SellerTierCrudSqlBindings.OperationNames.GetByPk, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerTier.Crud.GetByPk);
                var p = new DynamicParameters();
                p.Add(SellerTierCrudSqlBindings.IdParameterName, id);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var row = await connection.QuerySingleOrDefaultAsync<QcEntity.SellerTier>(sql, p);
                return row == null ? CreateNotFoundResponse<SellerTierDto>("Not found in SellerTier") : new RepoResponse<SellerTierDto>(row.ToDto());
            });
        }

        public async Task<RepoResponse<List<SellerTierDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling(SellerTierCrudSqlBindings.OperationNames.Select, async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SellerTierDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var sql = SqlLoader.Load(SqlScripts.SellerTier.Crud.List);
                var p = new DynamicParameters();
                AddCrudListPaginationParameters(p, pageNumber, pageSize);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var rows = await connection.QueryAsync<QcEntity.SellerTier>(sql, p);
                return new RepoResponse<List<SellerTierDto>>(rows.Select(r => r.ToDto()).ToList());
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling(SellerTierCrudSqlBindings.OperationNames.Count, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SellerTier.Crud.Count);
                await using var connection = await _connectionFactory.CreateReadConnectionAsync();
                var count = await connection.ExecuteScalarAsync<int>(sql);
                return new RepoResponse<int>(count);
            });
        }
    }
}