// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.SellerPayout
{
    public class GetByPeriodQuery : IRequest<Response<List<GetByPeriodResponseDto>>>
    {
        public int SellerPayoutPayoutPeriodId { get; set; }
        public int? pageNumber { get; set; }
        public int? pageSize { get; set; }

        public GetByPeriodQuery(int sellerPayoutPayoutPeriodId, int? pageNumber, int? pageSize)
        {
            this.SellerPayoutPayoutPeriodId = sellerPayoutPayoutPeriodId;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }

        public class GetByPeriodHandler : IRequestHandler<GetByPeriodQuery, Response<List<GetByPeriodResponseDto>>>
        {
            private readonly ILogger<GetByPeriodHandler> _logger;
            private readonly ISellerPayoutRepository _repository;
            public GetByPeriodHandler(ILogger<GetByPeriodHandler> logger, ISellerPayoutRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<List<GetByPeriodResponseDto>>> Handle(GetByPeriodQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.GetByPeriodAsync(request.SellerPayoutPayoutPeriodId, request.pageNumber, request.pageSize);
                return returnValue.ToResponse();
            }
        }
    }
}