// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.SellerPayout;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.SellerPayout
{
    public class TotalCountSellerPayoutQuery : IRequest<Response<int>>
    {
        public TotalCountSellerPayoutQuery()
        {
        }

        public class TotalCountSellerPayoutHandler : IRequestHandler<TotalCountSellerPayoutQuery, Response<int>>
        {
            private readonly ILogger<TotalCountSellerPayoutHandler> _logger;
            private readonly ISellerPayoutRepository _repository;
            public TotalCountSellerPayoutHandler(ILogger<TotalCountSellerPayoutHandler> logger, ISellerPayoutRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(TotalCountSellerPayoutQuery request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.CountAsync();
                return returnValue.ToResponse();
            }
        }
    }
}