// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.PricingEngineModule.Domain.Entities;
using QuickCode.Demo.PricingEngineModule.Application.Interfaces.Repositories;
using QuickCode.Demo.PricingEngineModule.Application.Dtos.CategoryCommissionOverride;
using QuickCode.Demo.PricingEngineModule.Domain.Enums;

namespace QuickCode.Demo.PricingEngineModule.Application.Features.CategoryCommissionOverride
{
    public class RemoveOverrideCommand : IRequest<Response<int>>
    {
        public int CategoryCommissionOverrideId { get; set; }

        public RemoveOverrideCommand(int categoryCommissionOverrideId)
        {
            this.CategoryCommissionOverrideId = categoryCommissionOverrideId;
        }

        public class RemoveOverrideHandler : IRequestHandler<RemoveOverrideCommand, Response<int>>
        {
            private readonly ILogger<RemoveOverrideHandler> _logger;
            private readonly ICategoryCommissionOverrideRepository _repository;
            public RemoveOverrideHandler(ILogger<RemoveOverrideHandler> logger, ICategoryCommissionOverrideRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<int>> Handle(RemoveOverrideCommand request, CancellationToken cancellationToken)
            {
                var returnValue = await _repository.RemoveOverrideAsync(request.CategoryCommissionOverrideId);
                return returnValue.ToResponse();
            }
        }
    }
}