// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.TransactionLedger;
using TransactionLedgerEntity = QuickCode.Demo.FinanceSettlementModule.Domain.Entities.TransactionLedger;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Mappings
{
    public static class TransactionLedgerMappings
    {
        public static List<TransactionLedgerDto> ToDto(this IEnumerable<TransactionLedgerEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TransactionLedgerDto ToDto(this TransactionLedgerEntity model)
        {
            return new TransactionLedgerDto
            {
                Id = model.Id,
                SellerId = model.SellerId,
                TransactionType = model.TransactionType,
                Amount = model.Amount,
                ReferenceId = model.ReferenceId,
                ReferenceType = model.ReferenceType,
                Description = model.Description,
                TransactionDate = model.TransactionDate,
                CreatedDate = model.CreatedDate
            };
        }

        public static TransactionLedgerEntity ToEntity(this TransactionLedgerDto model)
        {
            return new TransactionLedgerEntity
            {
                Id = model.Id,
                SellerId = model.SellerId,
                TransactionType = model.TransactionType,
                Amount = model.Amount,
                ReferenceId = model.ReferenceId,
                ReferenceType = model.ReferenceType,
                Description = model.Description,
                TransactionDate = model.TransactionDate,
                CreatedDate = model.CreatedDate
            };
        }
    }
}