// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Linq;
using QuickCode.Demo.Application.Contracts.Mediator;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.FinanceSettlementModule.Domain.Entities;
using QuickCode.Demo.FinanceSettlementModule.Application.Interfaces.Repositories;
using QuickCode.Demo.FinanceSettlementModule.Application.Dtos.CommissionEntry;
using QuickCode.Demo.FinanceSettlementModule.Domain.Enums;

namespace QuickCode.Demo.FinanceSettlementModule.Application.Features.CommissionEntry
{
    public class InsertCommissionEntryCommand : IRequest<Response<CommissionEntryDto>>
    {
        public CommissionEntryDto request { get; set; }

        public InsertCommissionEntryCommand(CommissionEntryDto request)
        {
            this.request = request;
        }

        public class InsertCommissionEntryHandler : IRequestHandler<InsertCommissionEntryCommand, Response<CommissionEntryDto>>
        {
            private readonly ILogger<InsertCommissionEntryHandler> _logger;
            private readonly ICommissionEntryRepository _repository;
            public InsertCommissionEntryHandler(ILogger<InsertCommissionEntryHandler> logger, ICommissionEntryRepository repository)
            {
                _logger = logger;
                _repository = repository;
            }

            public async Task<Response<CommissionEntryDto>> Handle(InsertCommissionEntryCommand request, CancellationToken cancellationToken)
            {
                var model = request.request;
                var returnValue = await _repository.InsertAsync(model);
                return returnValue.ToResponse();
            }
        }
    }
}