// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.ProductVariant;
using QuickCode.Demo.ProductCatalogModule.Application.Mappings;
using QuickCode.Demo.ProductCatalogModule.Persistence.Sql;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Persistence.Repositories
{
    public partial class ProductVariantRepository : BaseRepository, IProductVariantRepository
    {
        public async Task<RepoResponse<int>> UpdateStockAsync(int productVariantId, UpdateStockRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProductVariantCrudSqlBindings.OperationNames.UpdateStock, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductVariant.Command.UpdateStock);
                var parameters = new
                {
                    PRODUCT_VARIANT_STOCK_QUANTITY = updateRequest.ProductVariantStockQuantity,
                    PRM_PRODUCT_VARIANT_ID = productVariantId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> UpdatePriceAsync(int productVariantId, UpdatePriceRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProductVariantCrudSqlBindings.OperationNames.UpdatePrice, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductVariant.Command.UpdatePrice);
                var parameters = new
                {
                    PRODUCT_VARIANT_PRICE = updateRequest.ProductVariantPrice,
                    PRM_PRODUCT_VARIANT_ID = productVariantId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int productVariantId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProductVariantCrudSqlBindings.OperationNames.Deactivate, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductVariant.Command.Deactivate);
                var parameters = new
                {
                    PRM_PRODUCT_VARIANT_ID = productVariantId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}