// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.ProductCatalogModule.Domain.Entities;
using QuickCode.Demo.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using QuickCode.Demo.Infrastructure.Data;
using QuickCode.Demo.Infrastructure.Data.Extensions;
using QuickCode.Demo.Infrastructure.Data.Helpers;
using QuickCode.Demo.ProductCatalogModule.Application.Dtos.Product;
using QuickCode.Demo.ProductCatalogModule.Application.Mappings;
using QuickCode.Demo.ProductCatalogModule.Persistence.Sql;
using QuickCode.Demo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.Demo.ProductCatalogModule.Persistence.Repositories
{
    public partial class ProductRepository : BaseRepository, IProductRepository
    {
        public async Task<RepoResponse<int>> ApproveAsync(int productId, ApproveRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProductCrudSqlBindings.OperationNames.Approve, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.Approve);
                var parameters = new
                {
                    PRM_PRODUCT_ID = productId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> RejectAsync(int productId, RejectRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProductCrudSqlBindings.OperationNames.Reject, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.Reject);
                var parameters = new
                {
                    PRM_PRODUCT_ID = productId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }

        public async Task<RepoResponse<int>> SetFeaturedAsync(int productId, SetFeaturedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling(ProductCrudSqlBindings.OperationNames.SetFeatured, async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Product.Command.SetFeatured);
                var parameters = new
                {
                    PRODUCT_IS_FEATURED = updateRequest.ProductIsFeatured,
                    PRM_PRODUCT_ID = productId
                };
                await using var connection = await _connectionFactory.CreateWriteConnectionAsync();
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result);
            });
        }
    }
}