// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Demo.OrderManagementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class ReturnRequest
    {
        public static class Command
        {
            private const string _prefix = "OrderManagementModule.ReturnRequest.Command";
            private const string _sqlScriptStem = "ReturnRequest";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string Approve => ResourceKey($"{_sqlScriptStem}.Approve.g.sql");
            public static string Reject => ResourceKey($"{_sqlScriptStem}.Reject.g.sql");
            public static string Complete => ResourceKey($"{_sqlScriptStem}.Complete.g.sql");
        }
    }
}