// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo.Application.Contracts;
using QuickCode.Demo.SellerManagementModule.Domain.Entities;
using QuickCode.Demo.SellerManagementModule.Application.Dtos.SellerPerformanceReview;
using System.Threading.Tasks;
using QuickCode.Demo.SellerManagementModule.Domain.Enums;

namespace QuickCode.Demo.SellerManagementModule.Application.Interfaces.Repositories
{
    public partial interface ISellerPerformanceReviewRepository : IBaseRepository<SellerPerformanceReviewDto>
    {
        Task<RepoResponse<SellerPerformanceReviewDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetBySellerIdResponseDto>>> GetBySellerIdAsync(int sellerPerformanceReviewSellerId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetSellerAverageRatingResponseDto>> GetSellerAverageRatingAsync(int sellerPerformanceReviewSellerId);
    }
}