// <auto-generated>
// QuickCode — DO NOT EDIT
// This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
// Where to put custom code: see AGENTS.md at repo root.
// </auto-generated>
namespace QuickCode.Demo.FinanceSettlementModule.Persistence.Sql;
public static partial class SqlScripts
{
    public static partial class PayoutLineItem
    {
        public static class Query
        {
            private const string _prefix = "FinanceSettlementModule.PayoutLineItem.Query";
            private const string _sqlScriptStem = "PayoutLineItem";
            private static string ResourceKey(string sqlName) => $"{_prefix}.{sqlName}";
            public static string GetByPayoutId => ResourceKey($"{_sqlScriptStem}.GetByPayoutId.g.sql");
            public static string GetByOrderId => ResourceKey($"{_sqlScriptStem}.GetByOrderId.g.sql");
            public static string GetTotalByPayout => ResourceKey($"{_sqlScriptStem}.GetTotalByPayout.g.sql");
            public static string GetHighValueItems => ResourceKey($"{_sqlScriptStem}.GetHighValueItems.g.sql");
        }
    }
}