-- <auto-generated>
-- QuickCode — DO NOT EDIT
-- This file is regenerated by QuickCode. Edit DBML/DSL/templates or add user .cs files instead.
-- Where to put custom code: see AGENTS.md at repo root.
-- </auto-generated>
SELECT TOP 1 SUM(PLI.[NET_AMOUNT]) AS TOTAL_NET,
	SUM(PLI.[COMMISSION_AMOUNT]) AS TOTAL_COMMISSION,
	SUM(PLI.[ADJUSTMENT_AMOUNT]) AS TOTAL_ADJUSTMENTS 
FROM [PAYOUT_LINE_ITEMS] PLI 
WHERE PLI.[IsDeleted] = 0 
	AND PLI.[PAYOUT_ID] = @PRM_PAYOUT_LINE_ITEM_PAYOUT_ID 